### ISSUE TITLE
Fix PyPI auto deployment

### ISSUE THREAD

**Issue by alkovpro** [devopshq/artifactory#1]
1. check and fix pypi authorization in travis config
2. fix markdown readme generation

**Comment by Tim55667757** [comment]
Fixed in #2 issue:
link to build in index: https://pypi.python.org/pypi/dohq-artifactory
link to build with fix: https://pypi.python.org/pypi/dohq-artifactory/0.2.10

Deploy secret changed to devopshq
travis-ci build success: https://travis-ci.org/devopshq/artifactory/jobs/227958590#L578
