### ISSUE TITLE
artifactory.py fails to load with the newest python libraries on import urllib.parse

### ISSUE THREAD

**Issue by anaperic** [devopshq/artifactory#102]
Hi Team,

Was running my (working code) that uses your library, but with updated library versions.
When I try to use the library error I get is (quick test showcase):
```
>>> from artifactory import ArtifactoryPath
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/.local/lib/python2.7/site-packages/artifactory.py", line 39, in <module>
    import urllib.parse
ImportError: No module named parse
```
Seems someone added this line in commit:
https://github.com/devopshq/artifactory/commit/5b6ecc16708d6e797504f05d9a40ec1e4b55b136#diff-5979654d2532487ed87ebf2a0492cb08

And it's breaking the entire library (line 39).

- Versions that I tried and don't work: 0.5.241 (the newest)
- Versions I know works and isn't broken: 0.4.108 

Thank you & br,
Ana

**Comment by nikolasj** [comment]
@anaperic Can you use python3?
[since 2020 there will be no official support for python2.7](https://pythonclock.org/)
