### ISSUE TITLE
[question] Delete empty folders

### ISSUE THREAD

**Issue by trmendes** [devopshq/artifactory#104]
After I end up the unlink of old artifacts I end up with a repository full of empty folders. Is there a way to clean those empty folders using this python lib? Any AQL to list empty folders only?

**Comment by nikolasj** [comment]
@trmendes we use the plugin https://github.com/jfrog/artifactory-user-plugins/tree/master/cleanup/deleteEmptyDirs to delete empty folders

useful links:
https://jfrog.com/knowledge-base/empty-folder-clean-up/
https://www.jfrog.com/jira/browse/RTFACT-13618

**Comment by nikolasj** [comment]
@trmendes 
```python
# get all local repositories
r = self.artifactory_session.get("{}/api/repositories?type=local".format(self.artifactory_server))
r.raise_for_status()
content = r.json()

for repository in content:
    # delete empty folders
    url = '{}/api/plugins/execute/deleteEmptyDirsPlugin?params=paths={}'.format(self.artifactory_server,
                                                                                        repository['key'])
    r = self.artifactory_session.post(url)
    r.raise_for_status()
```

**Comment by alanyee** [comment]
Artifactory should garbage collect in 4 hours i.e. delete empty directories. Of course, if you want an immediate deletion, the above is a good approach.

**Comment by nikolasj** [comment]
@alanyee It seems that not in every version of the artifactory it works.
There were problems in later versions

**Comment by nikolasj** [comment]
@trmendes did we answer the question?

**Comment by trmendes** [comment]
hey @nikolasj. I'm very sorry for this late reply. It did. Thanks a lot for all your messages. I'm going to check the plugin :D
