### ISSUE TITLE
Python 3.6 compatibility; Path.glob()

### ISSUE THREAD

**Issue by allburov** [devopshq/artifactory#11]
https://github.com/Parallels/artifactory/issues/49
-----
Hi,

It appears that globbing behavior in Pathlib has changed/optimized to use scandir in 3.6: https://bugs.python.org/issue26032

```python
  File "/usr/lib/python3.6/pathlib.py", line 1081, in glob
    for p in selector.select_from(self):
  File "/usr/lib/python3.6/pathlib.py", line 489, in select_from
    scandir = parent_path._accessor.scandir
AttributeError: '_ArtifactoryAccessor' object has no attribute 'scandir'
```
Trivially implementing scandir on _ArtifactoryAccessor results in a second failure, so this may be more than just adding a new method that wraps listdir.

**Comment by Xcelled** [comment]
I have a workaround I posted on the other repo.

**Comment by allburov** [comment]
Hello, can yoi give link to commit with this fix or create pulk request?)

**Comment by Xcelled** [comment]
https://github.com/Parallels/artifactory/issues/49

It's hacky so I don't want to make a pull request as is. As I mention, I'm not even sure if this is the best way to implement `scandir`.

**Comment by kryzdof** [comment]
I tried your workaround and it worked fine for me.
I would recommend to put it in.
