### ISSUE TITLE
Cannot install dohq-artifactory via pip

### ISSUE THREAD

**Issue by ardyflora** [devopshq/artifactory#112]
Command tried:
``
 pip install dohq-artifactory==0.5.dev243
``

Error:

> Collecting dohq-artifactory==0.5.dev243
  Using cached https://files.pythonhosted.org/packages/dc/7d/38b21fa441a296b9274501c3cc1186bd1cafb39cb5ee3ad92435e4a73f49/dohq-artifactory-0.5.dev243.tar.gz
    Complete output from command python setup.py egg_info:
    This is local build
    error in dohq-artifactory setup command: 'install_requires' must be a string or list of strings containing valid project/version requirement specifiers
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-vkv9Z4/dohq-artifactory/

Also tried:
``
 pip install "dohq-artifactory==0.5.dev241"
``

Error:

> onx-rflora-01:scripts $ pip install "dohq-artifactory==0.5.dev241"
Collecting dohq-artifactory==0.5.dev241
  Could not find a version that satisfies the requirement dohq-artifactory==0.5.dev241 (from versions: 0.2.10, 0.2.15, 0.2.16, 0.2.26, 0.2.42, 0.2.48, 0.2.49, 0.2.59, 0.2.62, 0.2.65, 0.3.99, 0.3.101, 0.3.102, 0.3.103, 0.4.100, 0.4.101, 0.4.102, 0.4.103, 0.4.104, 0.4.105, 0.4.106, 0.4.107, 0.4.108, 0.4.109, 0.4.110, 0.4.111, 0.4.112, 0.4.113, 0.5.dev243, 0.5.dev244, 0.5.dev250, 0.5.dev251, 0.5.225, 0.5.227, 0.5.235, 0.5.241)
No matching distribution found for dohq-artifactory==0.5.dev241

**Comment by nikolasj** [comment]
@ardyflora 0.5.dev241 [does not exist](https://pypi.org/project/dohq-artifactory/#history). 
try it `pip install "dohq-artifactory==0.5.241"`.
What version of pip are you using and for which python?
I downloaded `dohq-artifactory==0.5.dev241` for python.3.5, python.3.6, python.2.7.

**Comment by ardyflora** [comment]
Thank you so much @nikolasj, that command worked.

My pip was outdated, I have updated it to:

Successfully installed pip-19.3.1


Old version was:

> onx-rflora-01:~ $ pip --version
pip 8.1.2 from /usr/lib/python2.7/site-packages (python 2.7)
