### ISSUE TITLE
making directory incorrectly

### ISSUE THREAD

**Issue by wym2010** [devopshq/artifactory#114]
I have used path.mkdir() to create directory, but...
I found the directory name was foo/bar, I can't understand why slash get inside of a directory name....

**Comment by wym2010** [comment]
ok, the issue only exists in webapp for artifactory not in url

**Comment by fuzzmz** [comment]
@wym2010, for what it's worth and in case this is still relevant, you can disable that behavior by unchecking Compress Empty Folders in the Sort & Filter pane.

![asd](https://user-images.githubusercontent.com/1335181/70231369-dec66800-1762-11ea-8856-827baf62303a.PNG)

**Comment by 0x6d64** [comment]
I believe this is not a bug at in this github project but a slightly confusing way how the artifactory web UI displays stuff? In this case I think this issue can be closed.
