### ISSUE TITLE
Bug with parsing urls that is not specified in ~/.artifactory_python.cfg

### ISSUE THREAD

**Issue by alanyee** [devopshq/artifactory#115]
```
from artifactory import ArtifactoryPath

aql = ArtifactoryPath("https://test-art.jfrog.io/test")
print(aql) # ArtifactoryPath("https://test-art.jfrog.io/test/")
```

I am pretty sure the error arises from that `/` that is added at the end of the url. Normally `ArtifactoryPath` urls objects do not have a slash at the end. This ends up leading to methods i.e. `find_user()` and `find_permission_target` returning `None`.

Having `~/.artifactory_python.cfg` contain `[https://test-art.jfrog.io/test]` is workaround that allows `find_user()` and `find_permission_target` to return actual values.

**Comment by alanyee** [comment]
```
from artifactory import ArtifactoryPath

aql = ArtifactoryPath("https://test.jfrog.io/test")
print(aql) # ArtifactoryPath("https://test.jfrog.io/test/")
```
Seems like the problem exists for any url that is not specified in the config file.

**Comment by allburov** [comment]
Could you test the develop branch of the library for Artifactory SaaS?

https://github.com/devopshq/artifactory#artifactory-saas
```python
# pip install git+https://github.com/devopshq/artifactory.git
from artifactory import ArtifactorySaaSPath

# API_KEY
path = ArtifactorySaaSPath(
    "https://myartifactorysaas.jfrog.io/myartifactorysaas/folder/path.xml",
    apikey="MY_API_KEY",
)
```
