### ISSUE TITLE
Creating Artifactory Remote Repositories

### ISSUE THREAD

**Issue by predatorian3** [devopshq/artifactory#116]
Is there any way to create remote repositories in Artifactory? I see how to do `dohq_artifactory.RepositoryLocal` and `dohq_artifactory.RepositoryVirtual` but not anything Remote.

**Comment by alanyee** [comment]
It does not seem implemented in this library, but https://www.jfrog.com/confluence/display/RTF/Repository+Configuration+JSON#RepositoryConfigurationJSON-application/vnd.org.jfrog.artifactory.repositories.RemoteRepositoryConfiguration+json details how you can do and make a PR to this repo on the feature.

**Comment by predatorian3** [comment]
I will attempt to work on that when I can. My work hasn't made it a priority yet and it was more of a nicety for us. However, I do want to see if I can get this functionality added.

**Comment by alanyee** [comment]
@predatorian3 you could try #117. I have not tested it myself, but you can.

**Comment by allburov** [comment]
Merged https://github.com/devopshq/artifactory/pull/117
