### ISSUE TITLE
aql: add more examples, and add support to debug, such as printing built query string

### ISSUE THREAD

**Issue by LeiYangGH** [devopshq/artifactory#131]
when trying aql, with include, sort, and limit, I wasted a lot of efforts guessing what python equivalent syntax would be given the raw aql string.

I always got below error until I went over some issues and came up with the right solution:

> requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: myhost/artifactory/api/search/aql

The error message is too general.

Could it be more acurate? such as some debugging functions to print the generated raw aql string?
And could any one add some example in readme? (if you allow, i'd like to add one example).

**Comment by allburov** [comment]
May be enable debug logging for `requests` could help you for the moment? https://gist.github.com/Daenyth/b57f8522b388e66fcf3b

>if you allow, i'd like to add one example

We have some examples in documentation with `include`, but it can don't cover enough https://devopshq.github.io/artifactory/#artifactory-query-language

Of course, feel free to contribute documentation and code!

**Comment by beliaev-maksim** [comment]
now is added to develop branch

will be added in next release
