### ISSUE TITLE
AQL issue

### ISSUE THREAD

**Issue by mpender** [devopshq/artifactory#138]
Seeing this 'AttributeError: 'ArtifactoryPath' object has no attribute 'aql''

When i try to use 

#!/usr/bin/env python3

from artifactory import ArtifactoryPath
art_url = "https://artifactory.example.com"

aql = ArtifactoryPath(art_url, auth=("user", "password"))
artifacts = aql.aql("items.find", {"repo": "my-repo"})

pip freeze | grep artifactory
dohq-artifactory==0.7.dev0

python 3.7.5

**Comment by allburov** [comment]
It seems like you've installed `dohq-artifactory` over old library is called `artifactory`. Could you create new venv and repeat steps to reproduce bug?

**Comment by allburov** [comment]
@mpender could you try to recreate venv and repeat? 
Otherwise I'll close the issue.
