### ISSUE TITLE
find_repository_<local || remote || virtual> return the same result

### ISSUE THREAD

**Issue by EslamElHusseiny** [devopshq/artifactory#143]
Hi all,
I've found that `find_repository_local`, `find_repository_remote`, and `find_repository_virtual` return the same result for any repo.
e.g.
```
from artifactory import ArtifactoryPath

art = ArtifactoryPath("URL", api_key="API_KEY")

res = art.find_repository_local('virtual-repo') ## virtual-repo is a virtual repo
res.raw['rclass'] 
'virtual'

res = art.find_repository_virtual('remote-repo') ## remote-repo is a remote repo
res.raw['rclass'] 
'remote'

res = art.find_repository_remote('local-repo') ## local-repo is a local repo
res.raw['rclass'] 
'local'
```

Am I doing anything wrong?

**Comment by allburov** [comment]
Hey there!
They have a different type. 
```python
type(res)
```

Probably, we should create the one method `find_repository` and choise type dynamicly by the attribute 'rclass' or 'type'. Like I've mentioned at this PR: https://github.com/devopshq/artifactory/pull/141#discussion_r386951465

**Comment by EslamElHusseiny** [comment]
The type is misleading cause using any of `find_repository_<>` returns a value regardless of the type of repository. Maybe replacing `find_repository_<>` with a generic `find_repository()` would be better.
