### ISSUE TITLE
_read_response() populates attribute layoutName instead of repoLayoutRef

### ISSUE THREAD

**Issue by staffanf** [devopshq/artifactory#146]
In [RepositoryLocal](https://github.com/devopshq/artifactory/blob/master/dohq_artifactory/admin.py#L369) and [RepositoryRemote](https://github.com/devopshq/artifactory/blob/master/dohq_artifactory/admin.py#L503), the attribute layoutName is populated instead of repoLayoutRef. 

This means that when we read back an object (e.g. in find_repository_local) we get the default repoLayoutRef instead of the correct one.

**Comment by allburov** [comment]
Fixed by https://github.com/devopshq/artifactory/pull/149
