### ISSUE TITLE
import urllib.parse throws exception in python2.7

### ISSUE THREAD

**Issue by chrbenisch** [devopshq/artifactory#147]
the import urllib.parse throws an exception in python 2.7.

this code is working instead:
```
try:
    from urllib.parse import urlparse
except ImportError:
     from urlparse import urlparse
```

**Comment by allburov** [comment]
@chrbenisch we don't support python 2.7, we do support 3.5. and higher versions. If you would like you could add compatibility for this version.  
Don't forget add CI-tests here https://github.com/devopshq/artifactory/blob/master/.travis.yml#L3

**Comment by allburov** [comment]
https://www.python.org/doc/sunset-python-2/#:~:text=As%20of%20January%201st%2C%202020,%2C%202019)%20and%20January%201st.
>As of January 1st, 2020 no new bug reports, fixes, or changes will be made to Python 2, and Python 2 is no longer supported.
