### ISSUE TITLE
SECURITY ISSUE

### ISSUE THREAD

**Issue by iaroslavscript** [devopshq/artifactory#148]
Hi!

Who is responsible for building pipeline/infrastructure? I want to report security issue. I will describe details in private mail.

**Comment by Tim55667757** [comment]
@iaroslavscript Hi! Write to me at "tgilmullin [at] ptsecurity.com" :)

**Comment by Tim55667757** [comment]
We carried out the necessary checks, now everything is fine. Thanks for the warning!
