### ISSUE TITLE
AttributeError: __enter__ raised when globing a path python3.8

### ISSUE THREAD

**Issue by thewamz** [devopshq/artifactory#156]
`path = ArtifactoryPath("http://repo.jfrog.org/artifactory/gradle-ivy-local")`
```
list(path.glob("*") 
```
or
```
for p in path.glob("*"):
    print(p)
```
raises an AttributeError: __enter__

**Comment by thewamz** [comment]
I am using python 3.8 by the way

**Comment by pawelrubin** [comment]
I've encountered the same issue.
```shell
- dohq-artifactory       0.7.330 
- python                 3.8.3
```
Traceback:
```shell
File ...:
    artifacts = sorted(path.glob("*.zip"), reverse=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1136, in glob
    for p in selector.select_from(self):
  File "/usr/local/lib/python3.8/pathlib.py", line 530, in _select_from
    with scandir(parent_path) as scandir_it:
AttributeError: __enter__
```

**Comment by pawelrubin** [comment]
I've added `@contextmanager` decorator to `_ArtifactoryAccessor.scandir`, however, it does not solve the issue.
Next issue I've encountered is:
```shell
File ...:
    artifacts = sorted(path.glob("*.zip"), reverse=True)
  File "/usr/local/lib/python3.8/pathlib.py", line 1136, in glob
    for p in selector.select_from(self):
  File "/usr/local/lib/python3.8/pathlib.py", line 531, in _select_from
    entries = list(scandir_it)
  File "/home/prubin/.cache/pypoetry/virtualenvs/source-QmnS7G-I-py3.8/lib/python3.8/site-packages/artifactory.py", line 1212, in __iter__
    for name in self._accessor.listdir(self):
  File "/home/prubin/.cache/pypoetry/virtualenvs/source-QmnS7G-I-py3.8/lib/python3.8/site-packages/artifactory.py", line 702, in listdir
    raise OSError(20, "Not a directory: %s" % str(pathobj))
NotADirectoryError: [Errno 20] Not a directory: https://artifactory-(...).zip
```

**Comment by pawelrubin** [comment]
@thewamz Could you provide the error traceback, please?

**Comment by thewamz** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-33-5dd310235db3> in <module>
----> 1 list(path.glob("*"))

/usr/lib/python3.8/pathlib.py in glob(self, pattern)
   1134             raise NotImplementedError("Non-relative patterns are unsupported")
   1135         selector = _make_selector(tuple(pattern_parts), self._flavour)
-> 1136         for p in selector.select_from(self):
   1137             yield p
   1138 

/usr/lib/python3.8/pathlib.py in _select_from(self, parent_path, is_dir, exists, scandir)
    528     def _select_from(self, parent_path, is_dir, exists, scandir):
    529         try:
--> 530             with scandir(parent_path) as scandir_it:
    531                 entries = list(scandir_it)
    532             for entry in entries:

AttributeError: __enter__

**Comment by pawelrubin** [comment]
Any progress on the issue? @allburov

**Comment by allburov** [comment]
@pawelrubin Hello! Could you test this branch with your environment and example? https://github.com/devopshq/artifactory/tree/support-python-38-glob

You can install it from git directly by:
```
pip uninstall dohq-artifactory
pip install git+https://github.com/devopshq/artifactory.git@support-python-38-glob
```

**Comment by pawelrubin** [comment]
@allburov Hi! It does work now, thank you!

**Comment by allburov** [comment]
Glad to hear this!
I'm going to publish new release on 02 June - https://github.com/devopshq/artifactory/pull/160
