### ISSUE TITLE
pool file created in empty debian repo with deploy_deb() instead of directory

### ISSUE THREAD

**Issue by kylekeppler** [devopshq/artifactory#157]
When using `deploy_deb` per the readme with an empty debian repo, a `pool` ***file***, not directory,  is created on the Artifactory remote.

**Comment by allburov** [comment]
It's a bug, we should fix it - the README.md's example is more clear and right to use

**Comment by kylekeppler** [comment]
Editing issue to be clearer.

**Comment by zhan9san** [comment]
@allburov 

IMHO, this is not a bug. There are some misunderstanding among `deploy`, `deploy_file` and `deploy_deb`. 

The methods above are to upload the given file to ArtifactoryPath. And only if the ArtifactoryPath instance exists and is a dir, the given file will be uploaded to that dir.

It's better to modify the example in README.md like #256
