### ISSUE TITLE
The read_config also should honor an apikey

### ISSUE THREAD

**Issue by stmlange** [devopshq/artifactory#158]
Hello, thank you for this project.

Rather a minor thing, but currently it looks like that the [read_config](https://github.com/devopshq/artifactory/blob/29c6da3b1f67967a3d537bf065cb3f69d8d96ab3/artifactory.py#L63)-method honors various variables. However as of now it seems that the configuration does not take a possible api-key into account. When setting the password to the API-Key I'll just get `400 Client Error: Bad Request for url`

E.g. allow:
```
[http://artifactory-instance.com/artifactory]
username = deployer
apikey = <secret-api-key>
verify = false
```

Thanks :-)

**Comment by beliaev-maksim** [comment]
@stmlange 
in artifactory password, API key, encrypted password are cross replaceable

have you just tried to set password = api_key ?

**Comment by stmlange** [comment]
Mhh based on my initial description it seems that I have tried that (`When setting the password to the API-Key I'll just get 400 Client Error: Bad Request for url`), however I was curious and tried it again and it seems to work.
So
```
[http://artifactory-instance.com/artifactory]
username = deployer
password = <secret-api-key>
verify = false
```
works. Perhaps updating the doc in the config section would help? Not sure, but I would be fine by just closing,

Thanks!

**Comment by beliaev-maksim** [comment]
@stmlange yes, I read the description, but that is the whole point how Artifactory works, that is why I decided to double check with you, since for me replace of password by API key works fine

may be there was some temprorary issue with JFrog rejecting api key? or some issue with this repo old version


@allburov 
please proceed to close the issue

**Comment by stmlange** [comment]
Yeah I don't know what the root cause was. The authentication is setup via LDAP so perhaps I was already locked out when trying the `password = <secret-api-key>` approach. Don't know.....anyhow it's working so I guess it doesn't matter what the root cause is.

Thanks for your feedback and input!
