### ISSUE TITLE
The source.copy(dest)-functionality should deploy artifacts with checksums

### ISSUE THREAD

**Issue by stmlange** [devopshq/artifactory#162]
Using
```
from artifactory import ArtifactoryPath
source = ArtifactoryPath("http://example.com/artifactory/builds/product/product/1.0.0/")
dest = ArtifactoryPath("http://example.com/artifactory/published/production/")
source.copy(dest)
```
Leads to warnings in Artifactory that the client hasn't published a checksum value (e.g. similar to this https://stackoverflow.com/questions/40009688)

Instead of directly deploying it, one would need to download the file, generate the checksum and the deploy it back. E.g.
```python
with TemporaryDirectory() as temp_dir:
    file_name_to_deploy = os.path.join(temp_dir, source.name)
    with source.open() as fobj, open(file_name_to_deploy, "wb") as out:
        out.write(fobj.read())
    dest.deploy_file(file_name_to_deploy, calc_md5=True, calc_sha1=True, calc_sha256=True)
```

(untested)

**Comment by sousajf1** [comment]
hello. can i take this one?

**Comment by allburov** [comment]
@sousajf1 we'll appreciate it! :) Feel free to create PR and show a solution!

**Comment by sousajf1** [comment]
https://github.com/devopshq/artifactory/pull/208

**Comment by beliaev-maksim** [comment]
@allburov 
I just tested on the instance of Artifactory

if artifact, that should be copied, doesn't have a checksum initially, then user gets warning that was mentioned
if artifact, has checksums, that were added during deploy, then the checksum are preserved during copy

from this test I assume that it is more like a user error. Initial artifact must have checksum calculated, before we copy.
if user wants to make copy with checksum, user needs to get path.stat() and then run `deploy_by_checksum` https://github.com/devopshq/artifactory/tree/develop#uploading-artifacts

I think we will not implement this, any objections?

**Comment by stmlange** [comment]
Hi,
all of our artifacts are deployed / uploaded with gradle and I'm fairly confident that all the artifacts have / had checksum's present.
Perhaps worth mentioning is that when I encountered the issue I was copying artifacts between two different instances. So something along the lines of:
```
from artifactory import ArtifactoryPath
source = ArtifactoryPath("http://some-instance.com/artifactory/foo/bar/1.0.0/")
dest = ArtifactoryPath("http://another-instance.com/artifactory/foo/bar/1.0.0/")
source.copy(dest)
```
Unfortunately I can't check anymore if this is actually true, since one of the instance was retired.
Based on the notes I have I had been using `dohq-artifactory==0.7.345` so perhaps the issue was already fixed.

Anyhow, feel free to close the issue.
If one really bothers about the checksums the mentioned work-around in my initial comment did the trick :-)

**Comment by beliaev-maksim** [comment]
@stmlange 
what you just mentioned makes a huge difference to the issue description

if instances are different, then completely different mechanism is utilized under the hood

**Comment by beliaev-maksim** [comment]
@stmlange 
available in develop branch
will be pushed to next release
