### ISSUE TITLE
RepositoryRemote._read_response() does not populate attribute url

### ISSUE THREAD

**Issue by staffanf** [devopshq/artifactory#164]
When looking at the fix for #146 I noticed a similar issue in RepositoryRemote.
The attribute url not populated when we read the from the remote .

This means that when we read back an object (e.g. in find_repository_remote) we get an url that is None instead of the correct one.

Maybe populate packageType also?

**Comment by dolfinus** [comment]
Fixed in https://github.com/devopshq/artifactory/pull/186 and https://github.com/devopshq/artifactory/pull/184

**Comment by beliaev-maksim** [comment]
@allburov 
can you please close this one, looks like that changes are already merged
