### ISSUE TITLE
For Debian packages, how to specify multiple components?

### ISSUE THREAD

**Issue by calvinatnvidia** [devopshq/artifactory#168]
I have packages that need to be tagged with multiple components. [REST API](https://www.jfrog.com/confluence/display/JFROG/Debian+Repositories#DebianRepositories-Specifyingmultiplelayouts) supports specifying `component` multiple times
`PUT "http://localhost:8081/artifactory/debian-local/pool/libatk1.0_i386.deb;deb.distribution=wheezy;deb.distribution=trusty;deb.component=main;deb.component=contrib;deb.architecture=i386;deb.architecture=64bit-arm"`

[In ArtifactoryPath](https://github.com/devopshq/artifactory/blob/master/artifactory.py#L1407), the properties (distribution, component, architecture) are dictionary keys. Since multiple keys of the same name can't be specified, I don't see a way to specify multiple components for a Debian package.

Is there a way to specify multiple components using ArtifactoryPath?

**Comment by dseifert** [comment]
Ditto for distributions. It is quite common that the same debian package is part of multiple distributions (e.g. data-only packages or just ones that are generic).

**Comment by dseifert** [comment]
Passing the arguments in as list should work (e.g. `deploy_deb(file_name, [ "wheezy", "trusty" ], ["contrib", "....`)

**Comment by allburov** [comment]
@Tim55667757 we should use the `Assignees` field more carefully. There're 4 assigned people, but there's no progress here yet.

Maybe a better way to use `Assignees` is to `assignee`  to someone when the person really is working on the issue? And if you want to say "Hey guys, look at the issue" just mention us :) Cause it makes our users think "Why they need 4 people to fix so small issue? And at least where is progress?"

What do you think?

**Comment by nacc** [comment]
I can confirm that passing an list does work.
