### ISSUE TITLE
Incorrect with statement in Downloading Artifacts section of the Documentation

### ISSUE THREAD

**Issue by nrundle** [devopshq/artifactory#170]
The Downloading Artifacts section of the documentation has a missing `open()` function name which results in an error if the code is run as is.

The statement currently reads:
```
with path.open() as fd, ("tomcat.tar.gz", "wb") as out:
```

Instead it should read:
```
with path.open() as fd, open("tomcat.tar.gz", "wb") as out:
```

**Comment by allburov** [comment]
Fixed by https://github.com/devopshq/artifactory/pull/171

I'm so glad when someone create an issue and fix it :)
