### ISSUE TITLE
Is there a way to collect and publish build information?

### ISSUE THREAD

**Issue by saggl** [devopshq/artifactory#172]
i would like to collect and publish the build information in addition to uploading and downloading artifacts. with the [CLI](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-BuildIntegration) from Jfrog this is possible as follows.
collect:
`` jfrog rt dl --buildname = "abc" --buildnumber = "1" test.zip #collect build infos to abc / 1``
publish:
`` jfrog rt bp abc 1 #publish build infos from abc / 1 '``

Is there a way to collect and publish build information with dohq-artifactory?

**Comment by beliaev-maksim** [comment]
please check if #248 solves your issue

**Comment by beliaev-maksim** [comment]
@allburov please close as addressed by #248

**Comment by beliaev-maksim** [comment]
addressed by #248
