### ISSUE TITLE
List files in archive (zip)

### ISSUE THREAD

**Issue by run2fail** [devopshq/artifactory#176]
Hi,

I know how to directly download files from a zip-archive stored in an Artifactory repository.

Is there any way to list the files in the zip-archive WITHOUT downloading the file? Does the Artifactory API provide this feature and is this also provided by the Python module?

Kind regards,

run2fail

**Comment by run2fail** [comment]
Hi,

sorry I don't want to nag you but can anyone answer this question? If this feature is not available in the Python module because it is also not provided by Artifactory, I would raise the issue to JFrog.

Kind Regards

**Comment by Tim55667757** [comment]
@run2fail Hi!

Do I understand the problem correctly, that you want to download a file inside the archive? Have you tried this https://stackoverflow.com/questions/47536315/download-single-file-from-zipped-artifactory-artifact using the following notation: ```http://localhost:8081/artifactory/repo-name/path/to/archive.zip!/path/to/file```

Or do you want to get a method in our library that will return you a list of all paths inside the archive?

**Comment by run2fail** [comment]
Hi @Tim55667757,

indeed I want to get a list of files/paths in the archive. In the Artifactory GUI you can browse archive contents (zip files in repositories of type generic) but I did not yet find a solution using the REST-API nor the Python module.

Rationale: The archives may be pretty large and even if they are small, you may not want to store them in /tmp just to get a list of files/paths.

Kind regards

**Comment by Tim55667757** [comment]
@run2fail I tried using the standard method ```walk(path)```

```
from artifactory import ArtifactoryPath, walk
from requests.auth import HTTPBasicAuth

path1 = ArtifactoryPath(
    r"https://repo.ptsecurity.ru/artifactory/reponame/directory/",
    auth=("user", "passwd"),
    auth_type=HTTPBasicAuth,
)

path2 = ArtifactoryPath(
    r"https://repo.ptsecurity.ru/artifactory/reponame/directory/archive.tgz!/",
    auth=("user", "passwd"),
    auth_type=HTTPBasicAuth,
)

path3 = ArtifactoryPath(
    r"https://repo.ptsecurity.ru/artifactory/reponame/directory/archive.tgz",
    auth=("user", "passwd"),
    auth_type=HTTPBasicAuth,
)

w1 = walk(path1)
w2 = walk(path2)
w3 = walk(path3)

for p1 in w1:
    print(p1)

for p2 in w2:
    print(p2)

for p3 in w3:
    print(p3)
```

In first case I received list of files in directory, but in second case I received ```FileNotFoundError: [Errno 2] No such file or directory``` error. Also in third case I received ```NotADirectoryError: [Errno 20] Not a directory``` error.

Unfortunately, Artifactory API does not return the contents of the archives, only the list of files in the directory. You can download and unpack an archive, as you said, or upload files to the repository without packaging and then access them using the ```walk()``` method.

**Comment by Tim55667757** [comment]
We will try to use AQL but do not promise result...

**Comment by apazdnikov** [comment]
curl -u admin:password http://127.0.0.1:8081/artifactory/api/search/aql -X POST -H 'Content-Type:text/plain' \
-d 'archive.entries.find({"archive.item.repo":{"$eq":"crosspm"},"archive.item.name":{"$eq":"artifactory-master.zip"}})'

```
{
  "results": [
    {
      "entry.name": ".gitignore",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": ".pre-commit-config.yaml",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": ".travis.yml",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "CHANGELOG.md",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "CONTRIBUTE.md",
      "entry.path": "artifactory-master/docs"
    },
    {
      "entry.name": "FAQ.md",
      "entry.path": "artifactory-master/docs"
    },
    {
      "entry.name": "LICENSE",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "MANIFEST.in",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "README.md",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "__init__.py",
      "entry.path": "artifactory-master/dohq_artifactory"
    },
    {
      "entry.name": "_config.yml",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "admin.py",
      "entry.path": "artifactory-master/dohq_artifactory"
    },
    {
      "entry.name": "artifactory.py",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "auth.py",
      "entry.path": "artifactory-master/dohq_artifactory"
    },
    {
      "entry.name": "conftest.py",
      "entry.path": "artifactory-master/tests"
    },
    {
      "entry.name": "exception.py",
      "entry.path": "artifactory-master/dohq_artifactory"
    },
    {
      "entry.name": "requirements-dev.txt",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "setup.cfg",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "setup.py",
      "entry.path": "artifactory-master"
    },
    {
      "entry.name": "test.cfg",
      "entry.path": "artifactory-master/tests"
    },
    {
      "entry.name": "test_admin.py",
      "entry.path": "artifactory-master/tests/integration"
    },
    {
      "entry.name": "test_artifactory_path.py",
      "entry.path": "artifactory-master/tests/unit"
    },
    {
      "entry.name": "test_exceptions.py",
      "entry.path": "artifactory-master/tests/unit"
    },
    {
      "entry.name": "test_integration_artifactory_path.py",
      "entry.path": "artifactory-master/tests/integration"
    },
    {
      "entry.name": "tox.ini",
      "entry.path": "artifactory-master"
    }
  ],
  "range": {
    "start_pos": 0,
    "end_pos": 25,
    "total": 25
  }
}
```
