### ISSUE TITLE
Create user with disabled profileUpdatable 

### ISSUE THREAD

**Issue by mo-saeed** [devopshq/artifactory#178]
Hello,

I am trying to create a user and I want to disable update_profile option but I can't do that when I init the USER class as it's set as default value, any workaround to set profileUpdatable to False

```
    def __init__(self, artifactory, name, email=None, password=None, disable_ui=False):
        super(User, self).__init__(artifactory)

        self.name = name
        self.email = email

        self.password = password
        self.admin = False
        self.profileUpdatable = True
        self.disableUIAccess = disable_ui
        self.internalPasswordDisabled = False
        self._groups = []

        self._lastLoggedIn = None
        self._realm = None

```

**Comment by mo-saeed** [comment]
@Tim55667757 Maybe you can help here :)

**Comment by Tim55667757** [comment]
@mo-saeed Hi! I'll try to see it :)

**Comment by fuzzmz** [comment]
If there's no one actively working on this I can take a swing at it.

**Comment by mo-saeed** [comment]
Would be great to have this implemented :)

**Comment by dolfinus** [comment]
It looks like this issue can be closed :-)
