### ISSUE TITLE
API Key for authentication

### ISSUE THREAD

**Issue by kumbasar** [devopshq/artifactory#18]
Hello,

Is it possible to enhance this module with the "API Key for authentication" feature?

Thanks,
volkan

**Comment by kryzdof** [comment]
Hi,

did you try to just use the auth parameter?
For me it works if I use
ArtifactoryPath(path, auth=("username", "API Key"))

greetings

**Comment by allburov** [comment]
@kumbasar Could you try the solution above? We will add it to the README, if it helped

**Comment by kumbasar** [comment]
The workaround is fine ;-)
