### ISSUE TITLE
AQL with sort and limit fails with bad request

### ISSUE THREAD

**Issue by Ashok82** [devopshq/artifactory#198]
response = path.aql("items.find" ,{"repo": {"$eq": "myrepo"}, "path": {"$match":"charts/pac19_2/2019-10-28-05-56-43*"},
      "name": {"$match": "*.tgz"},".sort": {"$desc":["created"]} })
    
raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url:

is this module supports complex AQL's any known issues ?? i want sort and limit ..sort({"$desc":["created"]}).limit(10)
any working example..

**Comment by dolfinus** [comment]
Hello.

There is an error in the request - you've added `.sort` field as a key of search query:
Instead of:
```python
response = path.aql(
    "items.find",
    {
        "repo": {"$eq": "myrepo"},
        "path": {"$match":"charts/pac19_2/2019-10-28-05-56-43*"},
        "name": {"$match": "*.tgz"},
        ".sort": {"$desc":["created"]}
    }
)
```

you should pass:
```python
response = path.aql(
    "items.find",
    {
        "repo": {"$eq": "myrepo"},
        "path": {"$match":"charts/pac19_2/2019-10-28-05-56-43*"},
        "name": {"$match": "*.tgz"},
    },
    ".sort",
    {"$desc":["created"]}
)
```

**Comment by Ashok82** [comment]
thanks , figured it
