### ISSUE TITLE
set retention policy

### ISSUE THREAD

**Issue by gilkatz** [devopshq/artifactory#199]
Hi
Is there a way to set the retention policy for files?

**Comment by allburov** [comment]
@gilkatz  
Hi! I see there is an issue about the retention policy in Artifactory https://www.jfrog.com/jira/browse/RTFACT-6723
Are you sure that we can set it manually in UI?

I'd recommend to use https://github.com/devopshq/artifactory-cleanup - it's a nice easy to easy cli-application. There isn't too much rules, but they cover 80% of our needing https://github.com/devopshq/artifactory-cleanup/tree/master/docs/RULES
Feel free to contribute if you create a rule!
