### ISSUE TITLE
Переименовать pypi-пакет в dohq_artifactory

### ISSUE THREAD

**Issue by allburov** [devopshq/artifactory#2]
**dohq_art** - непонятно что за "искусство" dohq, хочется видеть полное, без сокращений имя *dohq_artifactory*

**Comment by Tim55667757** [comment]
проверяй:
1. Переименовано в dohq_artifactory (старый билд тоже
2. Добавил автоинкремент билд-версии (как в кросспм и фаззи-классификаторе). Теперь в setup.py достаточно только мажор/минор менять: __version__ = '0.2'  # identify main version of dohq_artifactory
3. pip install dohq_artifactory локально у меня отработал:
!image.png!
4. Ссыль на индекс: https://pypi.python.org/pypi/dohq-artifactory
   Ссыль на версию: https://pypi.python.org/pypi/dohq-artifactory/0.2.10
5. Изменил деплйный секрет на devopshq
6. Сборка в тревисе успешна: https://travis-ci.org/devopshq/artifactory/jobs/227958590#L578
