### ISSUE TITLE
Release deployment is failing

### ISSUE THREAD

**Issue by dolfinus** [devopshq/artifactory#203]
https://github.com/devopshq/artifactory/pull/201 was merged into master branch. The CI/CD process linted source code, run tests, but failed on PyPi deployment stage:
https://travis-ci.org/github/devopshq/artifactory/jobs/743920563

Can you check it, please? Issue https://github.com/devopshq/artifactory/issues/200 is still in the latest package version due to that error.

**Comment by allburov** [comment]
@Tim55667757 could you or someone take a look? I won't have time till the next week...

**Comment by allburov** [comment]
There was an issue with travis https://travis-ci.community/t/cant-deploy-to-pypi-anymore-pkg-resources-contextualversionconflict-importlib-metadata-0-18/10494/24
Created a new commit in master, will be waiting https://travis-ci.org/github/devopshq/artifactory/builds/748299898

**Comment by dolfinus** [comment]
Looks great, thanks!
