### ISSUE TITLE
Set timeout while uploading file

### ISSUE THREAD

**Issue by akshaysarraf2016** [devopshq/artifactory#209]
I use ArtifactoryPath.deploy_file() to upload a file to artifactory. But I have a use case where I need to set a timeout to this function. So if the file upload doesn't finish in x seconds, it should timeout and move on to the rest of my script.
How can I set timeout in to deploy_file()? Is it supported natively?

**Comment by allburov** [comment]
Hi! It does not :( 
There's no way to set `timeout` in `requests.session` object. 

We should add `timeout` to the `ArtifactoryPath` and then provide it internally to every `session.get|post|put` requests
https://requests.readthedocs.io/en/master/user/advanced/#timeouts
```
path = ArtifactoryPath(
    "http://my-artifactory/artifactory/myrepo/restricted-path",
    auth=("USERNAME", "PASSWORD or API_KEY"),
    timeout=(1,10)
)
```

**Comment by akshaysarraf2016** [comment]
Okay, thank you for your response.
Is this something that you plan to add?

**Comment by allburov** [comment]
>Is this something that you plan to add?

Nope( It's why the issue has `help wanted` label. 
Feel free to contribute!

**Comment by akshaysarraf2016** [comment]
I'm new to this, created a pull request: https://github.com/devopshq/artifactory/pull/210
What do you think?

**Comment by akshaysarraf2016** [comment]
@allburov

1. Now that pull request is merged to develop branch, when do you think it can be merged to master?
2. Also, is there a plan to update pypi with this artifactory module: https://pypi.org/project/artifactory/ ?
    It still points to old outdated module.

**Comment by allburov** [comment]
1. It's merged and available as part of `dohq-artifactory` https://pypi.org/project/dohq-artifactory/0.7.508/
2. We do not update the `artifactory` pypi package, only `dohq-artifactory`. Use the latest, they are the same!
