### ISSUE TITLE
Download Docker artifacts as zip file

### ISSUE THREAD

**Issue by alivx** [devopshq/artifactory#216]
I'm trying to download docker images from Jfrog artifacts, but it fail every time.
```
    name="/tmp/artifactory/{0}-{1}".format("http://localhost/artifactory/micro/beko/urless/backend",idx)
    with path.download_folder_archive(archive_type="zip", check_sum=False) as archive:
        with open(r"{0}".format(name), "wb") as out:
            out.write(archive.read())
```

Error:

```
    909 
    910         if code != 200:
--> 911             raise RuntimeError(code)
    912 
    913         return raw

RuntimeError: 401

```

**Comment by allburov** [comment]
Are you able to download `manifest.json` inside this folder wtih no errors?

**Comment by allburov** [comment]
@vasokot could you (or a team member) try to download docker image from Artifactory? 
I don't have an installed Artifactory :(

**Comment by beliaev-maksim** [comment]
@alivx 
do you download a single file or a folder?
artifactory only supports archiving of folders

also, what is the artifactory version you have? just to ensure it supports archive method

**Comment by beliaev-maksim** [comment]
@alivx 
please try #272 and let us know if that works stably for you

also, 401 error code means that authentication failed. Have you added any required?
see here: https://github.com/devopshq/artifactory#authentication

**Comment by beliaev-maksim** [comment]
401 Unauthorized response is used for missing or bad authentication

403 Forbidden response should be used afterwards, when the user is authenticated but isn't authorized to perform the requested operation on the given resource
