### ISSUE TITLE
[Question] ArtifactorySaaSPath.get_groups() - 403 Forbidden

### ISSUE THREAD

**Issue by iiknd** [devopshq/artifactory#219]
Hi,

we have an SaaS license for the Artifactory.

```
# https://github.com/devopshq/artifactory#artifactory-saas
artifactory_ = ArtifactorySaaSPath("https://<address>/artifactory", apikey="1234567890abcdefg...")

# try to read the groups
artifactory_.get_groups()

    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 403 Client Error: Forbidden for url: https://<address>/artifactory/api/security/groups
```
The apikey is obtained from the Administration -> Access Tokens.
The user associated with the access token should have the necessary rights as when using the same user account it can browse through the groups and users.

Is there something done wrong then using the ArtifactorySaaSPath?

**Comment by allburov** [comment]
@unzap do others methods work? Are you able to download a file?

**Comment by allburov** [comment]
Does `get_groups` work with user\password combination well?

**Comment by unzap** [comment]
Hi,

I was able to get authentication working (Cloud/SaaS) with this combination:

`ArtifactorySaaSPath(url, auth=(user, token))`

After this all methods worked as documented!

With password the authentication failed, I had to use the token associated with the user.



Maybe the documentation could be updated a bit, it does not mention the "user" in the example?

```
from artifactory import ArtifactorySaaSPath

# API_KEY
path = ArtifactorySaaSPath(
    "https://myartifactorysaas.jfrog.io/myartifactorysaas/folder/path.xml",
    apikey="MY_API_KEY",
)
```

**Comment by beliaev-maksim** [comment]
@iiknd,
looking at JFrog docs I see that they mention that all on-premise API calls are valid.
https://www.jfrog.com/confluence/display/RTF6X/Artifactory+REST+API#ArtifactoryRESTAPI-WorkingwithArtifactorySaaS

in this case apikey should be valid authentication method:
https://www.jfrog.com/confluence/display/RTF6X/Artifactory+REST+API#ArtifactoryRESTAPI-Authentication

so cloud and on premise versions should be identical in this regard. Can you please do a test once again?
if it fails, probably would be good to double check with JFrog, maybe SaaS is limited on this auth type, then we will remove this auth method from the lib for SaaS
