### ISSUE TITLE
Add richer Group API request

### ISSUE THREAD

**Issue by norpol** [devopshq/artifactory#22]
**Update**: Just sent JFrog an E-Mail asking for documentation on this endpoint.

Currently `admin.py` is using the [only documented](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-GetGroupDetails) way of retrieving details of a group by calling the `api/security/group/<group id>` endpoint.

This endpoint doesn't provide any information on which users are in a group.

If you go into the Artifactory UI to Admin => Security => Groups => Group you'll see that you can indeed get from the backend which members are in a certain group.

Via. web-inspector you'll see that it's sending a request to `ui/groups/<group id>` which results in a richer JSON. I've also just tried accessing `api/groups/<group id>` which returns the similar JSON.

I've now checked their `application.wadl` and the endpoint is also mentioned there:

```xml
<resources base="http://localhost:8081/artifactory/api/">
<resource path="groups">
<method id="getGroups" name="GET">
<response><representation mediaType="application/json"/></response>
</method>
<method id="createGroup" name="POST"></method>
<resource path="delete"></resource>
<resource path="{id : [^/]+}">
</resource>
<resource path="{id: [^/]+}">
<method id="getGroup" name="GET">
<response><representation mediaType="application/json"/></response>
</method>
</resource>
</resource>
```

Example JSON of the undocumented endpoint:
```json
{
  "name": "example-group",
  "description": "My description",
  "autoJoin": false,
  "realm": "internal",
  "adminPrivileges": false,
  "external": false,
  "usersInGroup": [
    "user",
    "admin"
  ],
  "newUserDefault": false,
  "groupName": "example-group"
}
```

Example JSON of the currently used endpoint:
```json
{
  "name" : "example-group",
  "description" : "My description",
  "autoJoin" : false,
  "realm" : "internal",
  "adminPrivileges" : false
}
```

I've also just looked at what data the UI is sending, and it appears it's still sending `"autoJoin": false`, but not doing anything with this data in the UI. I think it is possible that `autoJoin` still exists, but is dropped in favor of the data that is send when you check `Automatically Join New Users to this Group` in the setting which is `newUserDefault`.
I've just send a request with `autoJoin: true` and `newUserDefault: false` which resulted in `newUserDefault` being what was used for storing the preference.

Telling by their old documentation:
`  - "autoJoin" : false (default, must be false if adminPrivileges is true),`

And clicking around in the Group setting I'm super confident that they've renamed the setting.

PUT into `/api/groups/example-group`
```json
{
  "name": "example-group",
  "description": "Example Description",
  "autoJoin": false,
  "realm": "internal",
  "adminPrivileges": false,
  "external": false,
  "usersInGroup": [],
  "newUserDefault": true,
  "groupName": "example-group"
}
```

**Comment by allburov** [comment]
Use undocumented API is bad practice, I think. 
For python-world remember `pip.main`-problem https://github.com/pypa/pip/issues/5240 

@norpol keep us informed that JFrog will respond to your mail

But if this functionality is critical and needed by the community, can we duplicate the class `Group` => `GroupUndocument`? 

1. After documenting this entrypoint, we can use class inheritance, and drop-down old entrypoint and use new. 

```python
class Group(AdminObject):
    def __init__():
        new code which use NEW DOCUMENTED entrypoint

class GroupUndocument(Group):
    # Class for backward compatibility
    # https://github.com/devopshq/artifactory/issues/22
    pass
```

2. If JFrog answer that we need only use what is documented - leave a new implementation for use at one's own risk :)
```python
class Group(AdminObject):
    def __init__():
        new code which use OLD DOCUMENTED entrypoint

class GroupUndocument(Group):
    def __init__():
        new code which use NEW UNDOCUMENTED entrypoint
````

@norpol what do you think about this?

**Comment by allburov** [comment]
Another plus for a double implementation - we do not exactly know in which version of the Artifactory introduced such an entrypoint...

**Comment by norpol** [comment]
@allburov Cool! I'm happy to adopt those changes, will force push this branch and bump here when I'm done with it.

**Comment by norpol** [comment]
Ok, just tested this code a little bit more :-).

## Caveats

`_create_and_update` paths are not persistent...
- create => `/api/groups`
- update => `/api/groups/<group name>`

`delete` has a two possible solutions:
- `/api/security/groups/<group name>` => supports sending DELETE request
- `/api/groups` => supports deleting multiple groups at the same time (consumes POST with list of groups as data)

**Comment by beliaev-maksim** [comment]
@allburov 
can you please close this one?
