### ISSUE TITLE
Support Builds API

### ISSUE THREAD

**Issue by josc-byte** [devopshq/artifactory#224]
does this wrapper support the builds API? (/api/builds/)

it alwayses prefixes the query with the /storage/api.

**Comment by allburov** [comment]
Nope, does not yet

**Comment by beliaev-maksim** [comment]
please check if #248 solves your issue

**Comment by beliaev-maksim** [comment]
@allburov please close as addressed by #248

**Comment by beliaev-maksim** [comment]
addressed by #248
