### ISSUE TITLE
Access Token Creation is broken

### ISSUE THREAD

**Issue by Jman420** [devopshq/artifactory#234]
The Access Token creation example is broken and results in the following error :
```
>>> newToken.create()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jgiannone\.virtualenvs\src-emO6ZSjr\lib\site-packages\dohq_artifactory\admin.py", line 99, in create
    self._create_and_update(self._session.put)
TypeError: _create_and_update() takes 1 positional argument but 2 were given
```

I believe the create() method needs to be overridden in the Token class.  It seems that https://github.com/devopshq/artifactory/blob/master/dohq_artifactory/admin.py#L99 is trying to call https://github.com/devopshq/artifactory/blob/master/dohq_artifactory/admin.py#L1057.

-----------

Also, when I try to call https://github.com/devopshq/artifactory/blob/master/dohq_artifactory/admin.py#L1057 directly on a Token object I get the following error : 
```
>>> newToken._create_and_update()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\jgiannone\.virtualenvs\src-emO6ZSjr\lib\site-packages\dohq_artifactory\admin.py", line 1089, in _create_and_update
    access_token_decoded = jwt.decode(access_token, verify=False)
  File "C:\Users\jgiannone\.virtualenvs\src-emO6ZSjr\lib\site-packages\jwt\api_jwt.py", line 119, in decode
    decoded = self.decode_complete(jwt, key, algorithms, options, **kwargs)
  File "C:\Users\jgiannone\.virtualenvs\src-emO6ZSjr\lib\site-packages\jwt\api_jwt.py", line 86, in decode_complete
    raise DecodeError(
jwt.exceptions.DecodeError: It is required that you pass in a value for the "algorithms" argument when calling decode().
```

**Comment by Jman420** [comment]
2nd issue resolved by downgrading PyJWT to version 1.7.1

**Comment by allburov** [comment]
@Jman420 did it work before ?

Can you try to add `*args, **kwargs` to `def _create_and_update(self):` method in Token and test it?

**Comment by Jman420** [comment]
I do not know if this worked before.  I only started using the package ~2days ago on the latest version.

But, your proposed fix worked.

Token._create_and_update() signature : 
`def _create_and_update(self, *args, **kwargs):`

Output : 
```
>>> newToken = Token(session, scope='api:* member-of-groups:readers', username='jman-test', expires_in=0)
>>> newToken.create()
>>> newToken.token_id
'0dbb8546-7347-45ab-818a-0322eea4cb3d'
```

**Comment by Jman420** [comment]
If anyone is looking for a patch fix while waiting for a release here is the patch I'm using : 

```
import logging

from dohq_artifactory import Token

# This class is a patch of the dohq_artifactory.Token class since its create functionality is broken in the current version.
class PatchedToken(Token):
    def create(self):
        logging.debug("Create {x.__class__.__name__} [{x.name}]".format(x=self))
        self._create_and_update()
```

**Comment by engnatha** [comment]
Surprised to see this closed. It's still an issue.

**Comment by allburov** [comment]
@engnatha thank you for the feedback! Do you have an idea how to fix the issue? 
We'd appreciate a pull request.

**Comment by engnatha** [comment]
Yeah, how can I get added to the project so I can push a new branch?

**Comment by allburov** [comment]
@engnatha you may create a fork and then create a PR from there
