### ISSUE TITLE
token for basic authentication

### ISSUE THREAD

**Issue by zhan9san** [devopshq/artifactory#267]
The official doc shows, [AccessTokens-BasicAuthentication](https://www.jfrog.com/confluence/display/JFROG/Access+Tokens#AccessTokens-BasicAuthentication)
> An access token can be used instead of a password for basic authentication.

It doesn't work when we call projects api.

```Python
>>> path = ArtifactoryPath("http://my-artifactory/artifactory/myrepo/restricted-path", auth=("USERNAME", "TOKEN"))
>>> path.find_project('foo')
```

It doesn't work thru `curl`
```
$ curl -uadmin:$token http://localhost:8081/access/api/v1/projects
{"errors":[{"code":"UNAUTHORIZED","detail":"Unauthorized","message":"HTTP 401 Unauthorized"}]}
```

Expected status code is 404 or 200, but get 401.

I think it's a bug of Artifactory

Besides, if we use `token` in header, it works
```
>>> path = ArtifactoryPath("http://my-artifactory/artifactory/myrepo/restricted-path", token="TOKEN")
>>> path.find_project('foo')
```

It works for users rest api
Using `curl` with `token` for basic authentication
```
curl -uadmin:$token http://localhost:8081/artifactory/api/security/users
```

Using python library with `token` for basic authentication
```
>>> path = ArtifactoryPath("http://my-artifactory/artifactory/myrepo/restricted-path", auth=("USERNAME", "TOKEN"))
>>> path.find_user('admin')
<User admin>
```

**Comment by allburov** [comment]
If `token="TOKEN` works in all endpoints - we can remove a use case`auth=("USERNAME", "TOKEN")` from README.md to reduce confusing. Only `token=` will be a valid usage for Token Based Authentication

**Comment by allburov** [comment]
@zhan9san Thank you!
