### ISSUE TITLE
Is it possible to run `dry-run` upload or copy?

### ISSUE THREAD

**Issue by arnisjuraga** [devopshq/artifactory#268]
Can I test uploads or move/copy by using some `dry-run`? 
E.g. - `jfrog-cli` has `--dry-run` switch, which simulates uploads/move/copy but does not change any data.

**Comment by zhan9san** [comment]
Hi @arnisjuraga 

Could you please explain the necessity to support `dry-run`? Could you list some specific scenarios?

If true, the command only indicates which artifacts would have been uploaded/moved/copied.
- [UploadingFiles](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-UploadingFiles): 
- [MovingFiles](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-MovingFiles)
- [CopyingFiles](https://www.jfrog.com/confluence/display/CLI/CLI+for+JFrog+Artifactory#CLIforJFrogArtifactory-CopyingFiles)


I am glad to implement it, if necessary.
