### ISSUE TITLE
Support for Deploy Artifact by Checksum

### ISSUE THREAD

**Issue by nathanperkins** [devopshq/artifactory#27]
What do you guys think about adding support for [deploying artifacts by checksum](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-DeployArtifactbyChecksum)? It uses the checksum to check if the artifact already exists on the server and copies it over to the new location without requiring the upload.

I think it'd be good to use for default behavior because the result is the same as a normal deploy, other than the fact that it doesn't require the client to upload.

**Comment by zhan9san** [comment]
I'll follow up this issue

**Comment by beliaev-maksim** [comment]
now is added to develop branch

will be added in next release
