### ISSUE TITLE
Tests - add coverage report to CI\CD

### ISSUE THREAD

**Issue by allburov** [devopshq/artifactory#275]
As proposed here https://github.com/devopshq/artifactory/pull/274#issuecomment-903004673

**Comment by allburov** [comment]
Actually, no one will look at them if it won't fail CI pipeline.

**Comment by beliaev-maksim** [comment]
@allburov 
there is a way, that you configure pipeline the way, that coverage from previous commit should not be less than in current

eg we had 81% coverage, I add code without tests, it drops to 78%, pipe fails and forces me to add tests

see example: https://github.com/getsentry/responses
