### ISSUE TITLE
Projects missing get_projects() method

### ISSUE THREAD

**Issue by rupaschomaker** [devopshq/artifactory#282]
Please add get_projects() similar to other get_foo() methods in artifactory.py

@zhan9san

**Comment by zhan9san** [comment]
Glad to do that.

**Comment by rupaschomaker** [comment]
Thank you for this and the other support for Projects

**Comment by zhan9san** [comment]
Thank @beliaev-maksim , #286 is merged into develop branch.
@rupaschomaker  Could you please verify this issue?
