### ISSUE TITLE
Support FileStatistics in Artifact stat

### ISSUE THREAD

**Issue by zhan9san** [devopshq/artifactory#288]
[FileStatistics](https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-FileStatistics)

Could you please assign this issue to me?

**Comment by zhan9san** [comment]
Thank you @beliaev-maksim 

Feel free to close this ticket

**Comment by beliaev-maksim** [comment]
pip install dohq-artifactory==0.8.0.dev0
