### ISSUE TITLE
minor issue when using / operator

### ISSUE THREAD

**Issue by gsemet** [devopshq/artifactory#29]
Hello

When using the / operator again a ArtifactoryPath without repository, the url seems wrong.
Example:
```python
>>> ArtifactoryPath(http://myartifactory.server.com/artifactory) / "reponame" / "path"
http://myartifactory.server.com/artifactoryreponame/path
```
Instead of `http://myartifactory.server.com/artifactoryreponame/path`.

If the `reponame` starts with a `/`, it works great:
```python
>>> ArtifactoryPath(http://myartifactory.server.com/artifactory) / "/reponame" / "path"
http://myartifactory.server.com/artifactory/reponame/path
```
This does not seem to have any impact on the api however.

**Comment by allburov** [comment]
@gsemet @oux fix added, could you test `develop` branch and give me feedback?

You can install it from git directly:
```
python -mpip install git+https://github.com/devopshq/artifactory.git#develop
```

**Comment by oux** [comment]
It works for me (linux) with your fix. Thanks !

**Comment by allburov** [comment]
Master also have fix. Thanks for a feedback!
