### ISSUE TITLE
Mutating `.properties` on an artifact should persist in Artifactory

### ISSUE THREAD

**Issue by OddBloke** [devopshq/artifactory#293]
Currently one has to write:

```py
props = artifact.properties
props['my-prop'] = 'value'
artifact.properties = props
```

This is a little confusing as, in Python, dicts are passed by reference so, normally, mutating them in one place in the code "persists" that mutation anywhere else they are referenced. I would prefer to be able to simply do:

```py
artifact.properties['my-prop'] = 'value'
```

**Comment by beliaev-maksim** [comment]
@OddBloke 
that was tough, you can consider stimulating development :D

please check https://github.com/beliaev-maksim/artifactory/tree/mbeliaev/update_props  branch on your side in case if that has some issues on your side

**Comment by beliaev-maksim** [comment]
@allburov
I don't like all these ideas with context managers and decorators

If number of connections is a concern when we directly change property, then I propose to reject this issue and not implement
Objections?

**Comment by allburov** [comment]
@beliaev-maksim anyway, let's move the changes for this issue in a new PR from https://github.com/devopshq/artifactory/pull/298
