### ISSUE TITLE
stat() now fails on paths with space (%20)

### ISSUE THREAD

**Issue by chibbert** [devopshq/artifactory#296]
This was working in: 0.7.630, but broken from pip release: 0.7.658

I'm not aware of any public artifactory servers that you could replicate the following test case against, but I'll outline the test case anyway:

```
artifactory_file_path="https://packages.companyname.com/artifactory/streamstore/streams/afolder/ANOTHER%20FOLDER/YETANOTHER%20FOLDER/FOLDER/example-file.ts"
artifactory_path = ArtifactoryPath(artifactory_file_path)
artifactory_path.stat()
```

When 0.7.630 is installed this works correctly.

When I update to 0.7.658 this fails with:
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/chibbert/venv_playout-image/lib/python3.8/site-packages/artifactory.py", line 1361, in stat
    return self._accessor.stat(pathobj=pathobj)
  File "/home/chibbert/venv_playout-image/lib/python3.8/site-packages/artifactory.py", line 751, in stat
    jsn = self.get_stat_json(pathobj)
  File "/home/chibbert/venv_playout-image/lib/python3.8/site-packages/artifactory.py", line 740, in get_stat_json
    raise OSError(2, "No such file or directory: '%s'" % url)
FileNotFoundError: [Errno 2] No such file or directory: 'https://packages.mediakind.com/artifactory/api/storage/api/storage/streamstore/streams/afolder/ANOTHER%20FOLDER/YETANOTHER%20FOLDER/FOLDER/example-file.ts'
```

I've identified the commit where this issue started occuring as a3c386a3af0f6cc820036108cac9ca5637fe01ce but couldn't spot anything obvious related to processing filenames.

If I do the same test, but with a filepath with no spaces (%20) characters in then this works fine in all versions.

I've also tested paths without spaces that are longer than the failing path and they work fine too.

**Comment by beliaev-maksim** [comment]
now we use URL percent encoding in the library.
please test following code:
~~~python
artifactory_file_path="https://packages.companyname.com/artifactory/streamstore/streams/afolder/ANOTHER FOLDER/YETANOTHER FOLDER/FOLDER/example-file.ts"
artifactory_path = ArtifactoryPath(artifactory_file_path)
artifactory_path.stat()
~~~

**Comment by chibbert** [comment]
Thanks so much for the fast reply. I've tested with the file path string using spaces (converted with urllib.parse.unquote) and this is working fine. Thank you for re-educating me :-)

**Comment by beliaev-maksim** [comment]
@chibbert 
no problem,
basically you need to take path from your arti:
![image](https://user-images.githubusercontent.com/51964909/135636361-83b02bb1-c711-4f2d-a6a4-aec7f9dbe78a.png)
