### ISSUE TITLE
Uploading to Pypi repository

### ISSUE THREAD

**Issue by mentaal** [devopshq/artifactory#30]
Hi, this isn't a bug but more a question on how to leverage this tool to interface to a PyPi repository on Artifactory. 

If I use the standard setuptools approach to upload a wheel: `python setup.py bdist_wheel upload ...`
The wheel gets uploaded and is searchable and downloadable via pip. This was done as a test with an initial 0.1 version of a module. 

I have tried this tool to upload a new version: 0.2 of the same module. On artifactory, I can see that it has been successfully uploaded and the tree looks correct:

Below are just made up names for illustration:

    module_name
         | ----0.1
         |     | module_0.1_wheel.whl
         | ----0.2
               | module_0.2_wheel.whl

However, the 0.2 version is searchable nor is it downloadable via pip. 

Is there an additional step that is required, after actually uploading the wheel? 

Thanks.

**Comment by mentaal** [comment]
Ah, if I add the properties pypi.summary, pypi.version, pypi.normalized.name and pypi.name to the wheel, it becomes available via pip.

**Comment by allburov** [comment]
@mentaal, thanks for feedback!
Pypi have multiple format - `whl, egg, tar.gz`. 
And I think it's too hard to support all of this, our library support Artifactory, not pypi.

Also, Artifactory can autoparse properties from whl path. We upload whl to path like below and Artifactrory after ~ 1 min set properties and package available in pypi-index
```
https://repo.example.ru/artifactory/webapp/#/artifacts/browse/tree/General/pypi-pypi/projectname/0.3.34193/projectname-0.3.34193-py3-none-any.whl
# where 
# projectname is pypi package name 
# version is pypi version
```

**Comment by mentaal** [comment]
Thanks @allburov, indeed I see that in the documentation but for some reason it wasn't working for me. Maybe just a problem with our installation of artifactory. 
Glad to hear that it works for you - and I agree - if it works then there is nothing extra to be done here!

**Comment by allburov** [comment]
Anyway, we add both method to FAQ.md, may be it will help other users :) Thanks!
