### ISSUE TITLE
Traceback on Python 3.10: TypeError: stat() missing required argument 'path' (pos 1)

### ISSUE THREAD

**Issue by OddBloke** [devopshq/artifactory#302]
We accidentally started using Python 3.10 to run our Artifactory-touching code and we hit the following traceback (I've removed the traceback lines from our code; it's just executing `touch` against the root path to check connectivity):

```pytb
  File "/usr/local/lib/python3.10/site-packages/artifactory.py", line 1684, in touch
    if self.exists() and not exist_ok:
  File "/usr/local/lib/python3.10/pathlib.py", line 1288, in exists
    self.stat()
  File "/usr/local/lib/python3.10/site-packages/artifactory.py", line 1413, in stat
    return self._accessor.stat(pathobj=pathobj)
TypeError: stat() missing required argument 'path' (pos 1)
```

(3.10 only released today, so I'm not expecting you to support it yet! Just figured I'd let you know at least part of what you'll hit.)

**Comment by beliaev-maksim** [comment]
release candidate
pip install dohq-artifactory==0.8.0.dev0
