### ISSUE TITLE
Move the repo to Github Actions

### ISSUE THREAD

**Issue by allburov** [devopshq/artifactory#308]
We need to move the repo to Github Actions. 

The only thing is left - deploy release package to pypi, @beliaev-maksim is it right?
Let's follow official guide and do it! https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

@Tim55667757 could you save credential for pypi in github secrets by following the instruction? https://packaging.python.org/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/#saving-credentials-on-github

**Comment by beliaev-maksim** [comment]
@allburov 
that is correct. I do not have access to secrets, so it will be on you :)

I am considering updating pre-commit CI also to GH actions, but this is low priority for now

**Comment by allburov** [comment]
>I am considering updating pre-commit CI 

[pre-commit.ci](https://pre-commit.ci/) handles hooks very good, doesn't it? I think it's the best place where we should put pre-commit checks :)

**Comment by beliaev-maksim** [comment]
@allburov 
they have a plugin for GHA as well. I use it in another project and works very good

I just prefer to have all CI from one provider

**Comment by Tim55667757** [comment]
I will generate a new token and gave it to @allburov

**Comment by allburov** [comment]
I've added `PYPI_API_TOKEN` to secret variables in the project

@Tim55667757 suggested not to use test pypi and releasing versions like other projects in devopshq do:
1. `develop` branch is released with `dev` suffix and build number at the end `dohq-artifactory==1.2.3.dev4`
2. `master` branch is release without suffix `dohq-artifactory==1.2.3` 

In this case each commit to develop will test "deploying" feature to pypi too.

I like this approach!

**Comment by beliaev-maksim** [comment]
@allburov @Tim55667757 
I am not confident that current approach of build publishing is correct

If you check `setup.py` you will see that versions for Wheel and for tarball will be different when you install it on the machine. (see [PyPi](https://pypi.org/project/dohq-artifactory/#files). tarball will always have 0.7.dev0, which is incorrect

we have to set version static, that means there are 3 options:
1. modify setup.py directly and set a version
2. create version.txt file
3. create `__version__` variable in `__init__.py` or in `artifactory.py`


next, usually pipeline is managed and triggered by tags. So, managing `.dev` becomes a bit more complicated.

**Comment by allburov** [comment]
Hi! Yep, it looks a bit complicated than it should...

Let's move current approach (with all it's bugs) to Github Actions first and then we'll improve it step by step.

With Travis CI we used the simple approach:
1. Increase minor version manually in https://github.com/devopshq/artifactory/blob/master/setup.py
2. Get build version from `TRAVIS_BRANCH` (https://github.com/devopshq/artifactory/blob/master/setup.py too)
3. Publish the release from all `master` commits to pypi.

We need to change Travis's variables to github's one and publish it via github actions

And it's the perfect workflow for me for a small project like this :)

**Comment by beliaev-maksim** [comment]
@allburov 
there is no such a thing like build number in GHA.
I do not know how to transfer current approach 1:1

**Comment by allburov** [comment]
Let's hardcode the version in setup.py then :) We don't release frequently
