### ISSUE TITLE
path.mkdir Causing Errors

### ISSUE THREAD

**Issue by GerhardArya** [devopshq/artifactory#311]
path.mkdir is causing errors more often than not.

My usage:

```
def upload_artifactory(filename, i):
    print("Uploading file " + filename + " to Artifactory...")
    filename_clean = remove_extension(filename)
    
    path = ArtifactoryPath(
        "https://<artifactoryaddress>/artifactory/<reponame>/<subdirectory>/"+filename_clean,
        apikey=os.environ['ARTIFACTORY_API_KEY']
    )

    if i == 0:
        path.mkdir()

    path.deploy_file("./temp/"+filename)
    print("Upload successful!")
```
This function is called several times within a for loop hence the input i. Path.mkdir() is called only for the first loop to create the folder for the archive files that are going to be deployed/uploaded there. This used to work no problem for the last several months before starting to cause errors recently.

The error in question:

> Traceback (most recent call last):
>   File "directories/upload_artifactory.py", line 63, in <module>
>     upload_artifactory(filename, i)
>   File "directories/upload_artifactory.py", line 43, in upload_artifactory
>     path.mkdir()
>   File "/usr/local/lib/python3.10/pathlib.py", line 1173, in mkdir
>     self._accessor.mkdir(self, mode)
> FileNotFoundError: [Errno 2] No such file or directory: 'https://artifactoryaddress/artifactory/reponame/subdirectory/filename_clean'

I think that my usage is fairly standard and that path.mkdir should create the new directory inside the Artifactory repository in the first loop before uploading (as it did and has done so many times before), so why is path.mkdir suddenly complaining "No such file or directory"?

**Comment by beliaev-maksim** [comment]
what is the version of artifactory are you using ?

what is the version of python?

**Comment by GerhardArya** [comment]
Artifactory is 7.27.10
Python is 3.10

**Comment by beliaev-maksim** [comment]
we do not have such a version, latest is 0.7.742
and it does not support Py3.10

either wait for 0.8 or you can test `develop` branch to see if that works for you

**Comment by GerhardArya** [comment]
Oooh, you mean the dohq-artifactory version? If so, it is version 0.7.742. So, this version doesn't support python 3.10? Would this be the cause for the errors? Which python version is supported?

**Comment by beliaev-maksim** [comment]
try latest develop
`pip install git+https://github.com/devopshq/artifactory.git@develop`

**Comment by GerhardArya** [comment]
It worked with that one. Would you recommend me to stick to using develop from now on? Or should I switch to 0.8 once it is released? Or should I somehow try to ensure that Python 3.9 is used instead of 3.10 but still use dohq-artifactory 0.7.742? 

I'm using this inside of gitlab ci.

**Comment by beliaev-maksim** [comment]
@GerhardArya 
just wait for 0.8

we will release it on days

**Comment by GerhardArya** [comment]
Will do! Closing the issue and thank again 👍

**Comment by beliaev-maksim** [comment]
here is a release candidate
pip install dohq-artifactory==0.8.0.dev0
