### ISSUE TITLE
move to CI

### ISSUE THREAD

**Issue by beliaev-maksim** [devopshq/artifactory#321]
@allburov @vasokot 
Now we have new pipeline which is based on `tags` and I do not see a big benefit of committing into `develop` over committing directly to `master`.
We no more decide when to publish based on merge of develop, but we can do it in any point of a time

propose:
1. delete `develop` branch
2. enable only `squash` commits in GitHub settings. This will preserve repository history clean and linear 
3. update documentation, telling that people can make PR directly to master

this will simplify overall workflow 

![image](https://user-images.githubusercontent.com/51964909/146148253-69816390-b4fb-45a2-bbe4-168bbf527e38.png)

**Comment by beliaev-maksim** [comment]
in addition would be good to add change log in GitHub releases page.

see #322

**Comment by allburov** [comment]
>delete develop branch
>update documentation

I like and have done it! 

As about merging strategy - I don't think that we need to restrict it to "squash only" policy. But we will squash PRs with a lot of "fix 1" "fix 2" commits if it's needed. 

>in addition would be good to add change log in GitHub releases page.

Good idea! Let's talk about changelog in the source issue #322

**Comment by beliaev-maksim** [comment]
@allburov 
I see most of projects on GH switch to squash. 
Even in case of changelog, this is a way easier to find what was changed, since with squash type, you basically need to add every commit to the changelog because each commit represents a fix or feature
