### ISSUE TITLE
any chance of maintaining the changelog?

### ISSUE THREAD

**Issue by dimbleby** [devopshq/artifactory#322]
Last entry is currently from April 2018.

Today I see that 0.8.0 was released.  Apparently it's a big enough change that it was worth bumping 0.7.x to 0.8.x; but I have no idea whether I can just take the new version or, if I do, what changes I should expect to have to make to my code.

Thanks!

**Comment by beliaev-maksim** [comment]
version notation: X.X.X -> backwards incompatible.feature.patch
0.7->0.8 is a feature, thus, backwards compatible

**Comment by dimbleby** [comment]
Good to know that you consider this backwards compatible, thanks!  A maintained changelog would be useful anyway, but it's reassuring for me to know that I can probably just take the bump.

(Even among those that do follow semantic versioning, conventions differ.  Eg in the Rust community, I _would_ expect 0.7 -> 0.8 to be breaking.)

**Comment by beliaev-maksim** [comment]
we changed the pipeline and CI process, so, we will try to make changelog in next release

**Comment by allburov** [comment]
I like the idea with changelog! We must provide at least CHANGELOG.mg file with manual notes

**Comment by beliaev-maksim** [comment]
@allburov 
would you like to create changelog retrospectively ?

**Comment by allburov** [comment]
@dimbleby 
I've created a record in the changelog for the latest (0.8.0) version. https://github.com/devopshq/artifactory/blob/master/CHANGELOG.md#080
Hope I didn't miss anything.

Now we will maintain it, TY!
