### ISSUE TITLE
AttributeError: 'ArtifactoryPath' object has no attribute 'read'

### ISSUE THREAD

**Issue by Gia-Vinh** [devopshq/artifactory#330]
Hi, I'm trying to modified the code block in the usage guide to download a folder:

```
from artifactory import ArtifactoryPath

# User and password OR API_KEY
path = ArtifactoryPath(
    "<artifactory_link>",
    (auth=("user", "password")),
)

with path.archive(archive_type="zip", check_sum=False).open() as archive:
    with open(r"C:\Users\vov4hc\Desktop\Test-download-script\test.zip", "wb") as out:
        out.write(archive.read())

# download folder archive in chunks
path.archive().writeto(out="my.zip", chunk_size=100 * 1024)
```
My current error is saying: AttributeError: 'ArtifactoryPath' object has no attribute 'read'

**Comment by beliaev-maksim** [comment]
please refer to documentation 
you use it incorrect

**Comment by Gia-Vinh** [comment]
```
from artifactory import ArtifactoryPath

path = ArtifactoryPath(
    "http://my_url:8080/artifactory/my_repo/winx64/aas", auth=("user", "password")
)

with path.archive(archive_type="zip", check_sum=False) as archive:
    with open(r"D:\target.zip", "wb") as out:
        out.write(archive.read())

# download folder archive in chunks
path.archive().writeto(out="my.zip", chunk_size=100 * 1024)
```
The code in the doc is here. I dont change much besides the url, and the directory path.

**Comment by beliaev-maksim** [comment]
![image](https://user-images.githubusercontent.com/51964909/147820749-71fc69d6-2e8b-45ba-92fc-4dcd93c20b5a.png)

**Comment by Gia-Vinh** [comment]
The open() is actually an attempt of mine to solve the error. I forgot to delete it before ask.

**Comment by beliaev-maksim** [comment]
does that work 
`path.archive().writeto(out="my.zip", chunk_size=100 * 1024)`
?

**Comment by beliaev-maksim** [comment]
I revert myself

read() is actually required and following snippet works fine for me:

```python
with path.archive(archive_type="zip", check_sum=False).open() as archive:
    with open(r"C:\target.zip", "wb") as out:
        out.write(archive.read())
```

**Comment by Gia-Vinh** [comment]
> does that work `path.archive().writeto(out="my.zip", chunk_size=100 * 1024)` ?

this works.

**Comment by beliaev-maksim** [comment]
@Gia-Vinh 
can you try snippet from above with `read()` as well ?

if fails, what is the stack trace?

**Comment by Gia-Vinh** [comment]
```
with path.archive(archive_type="zip", check_sum=False).open() as archive:
    with open(r"C:\target.zip", "wb") as out:
        out.write(archive.read())
```
It works. 
Thanks.

**Comment by beliaev-maksim** [comment]
great, we will update docs to reflect the change

happy new year!
