### ISSUE TITLE
Where can I put .artifactory_python.cfg in windows?

### ISSUE THREAD

**Issue by rootjammy** [devopshq/artifactory#335]
.artifactory_python.cfg seems is arbitrary  a file in this module, is it necessary or do we have any method to disable this? I put .artifactory_python.cfg in  C:\Users\{MY_ACCOUNT}, but it doesn't help.

Can anyone help on this?

Thanks!

**Comment by beliaev-maksim** [comment]
it looks to be a bug on Windows

it will not recognize the file. We will fix it in the next release

you will need to manually override the value of https://github.com/devopshq/artifactory/blob/fdc1115884559f6b2123015288301d080aaa03e4/artifactory.py#L65


in your script:

```python
import artifactory
artifactory.default_config_path = "~\\.artifactory_python.cfg"
```

**Comment by eraccn** [comment]
Thank you for this help.
