### ISSUE TITLE
add verify = False to bypass ssl certificate validation?

### ISSUE THREAD

**Issue by LeiYangGH** [devopshq/artifactory#342]
When the server ssl certificate expired, is there any way to bypass ssl certificate validation?
like verify = False parameter in requests module.

**Comment by zhan9san** [comment]
This may help you.

[ssl-cert-verification-options](https://github.com/devopshq/artifactory#ssl-cert-verification-options)

**Comment by LeiYangGH** [comment]
thanks! it worked!
