### ISSUE TITLE
test.zip leaks into source tree

### ISSUE THREAD

**Issue by jugmac00** [devopshq/artifactory#348]
# Reproduction

```
git clone ..
cd ..
tox -e py39
```
This creates a `test.zip` in the local source tree, which is not git-ignored.

## Suggestions
- use https://docs.pytest.org/en/latest/how-to/tmp_path.html
- or put it in .gitignore

**Comment by allburov** [comment]
@jugmac00 Hi, appreciate the feedback!
Could you create a PR with changes that fix the issue?
