### ISSUE TITLE
400 Client Error:  for url: https://my-artifactory/artifactory/api/search/aql

### ISSUE THREAD

**Issue by mrobertseidowsky-gpsw** [devopshq/artifactory#358]
Hello, sometimes I get this error while doing a request:
`400 Client Error:  for url: https://my-artifactory/artifactory/api/search/aql` 
(`my-artifactory` is changed locally of course)
It come and goes randomly without code change and can be blocking during long time.
What can I do?

**Comment by beliaev-maksim** [comment]
what is the minimal reproducible ?

**Comment by mrobertseidowsky-gpsw** [comment]
Hello, I'm sorry, my request was bad (using `1m` instead `1mo`) it's just that the error was not clear so I didn't suspect a syntax error in `created_last` field). Closing this ticket with my apologies.
