### ISSUE TITLE
I want to access latest build number , but no luck 

### ISSUE THREAD

**Issue by vinodneelakantam** [devopshq/artifactory#369]
Hello Team , 

I want to access latest artifacts or latest build number from artifactory  . But , no straight api for this  ?

for now , im using my own code - **but i honestly feel there should be better way** 

```
from artifactory import ArtifactoryPath

Project_Name_local = repository_dict_info["Project_Name"][repo.name]

    globe_path_arti_doc = artifactory_.glob(
        "*/" + str(Project_Name_local) + "/master/" + "**/" + "*doc*.zip") `

    #for artifact in artifactory_:
    for artifact in globe_path_arti_doc:
        stat_time = artifact.stat().ctime
        repository_dict_info["Doc"][repo.name] = True
        build_number_Global.append(artifact.properties["build.number"])
        build_date_UTC_Global.append(stat_time)
        try :
            repository_dict_info["latest_build_No"][repo.name] = max(build_number_Global)[0]
            repository_dict_info["Build_Stamp_Date"][repo.name] = max(build_date_UTC_Global)
            if (PRINT_DEBUG):
                print("Stats of this artificat ", artifact, stat_time)
                print("latest_build_INFO :",
                      repository_dict_info["latest_build_No"][Project_Name_local],
                      repository_dict_info["Build_Stamp_Date"][Project_Name_local])

**Comment by allburov** [comment]
@vinodneelakantam did you try to use AQL? https://www.jfrog.com/confluence/display/JFROG/Artifactory+Query+Language

**Comment by vinodneelakantam** [comment]
@allburov : I want this in python

**Comment by allburov** [comment]
@vinodneelakantam AQL is just a query language that this library also support - so just use AQL to sort your artifacts right and get the result! https://github.com/devopshq/artifactory#artifactory-query-language

I'm not sure that it support semver sorting for custom properties like `build.number` tho.
But if semver is only grows up with time - you can sort it by `created`

**Comment by allburov** [comment]
@vinodneelakantam any luck with AQL?

I'm closing the issue, we have enough examples about AQL in readme.md, you just need to experiment and find your own solution!
