### ISSUE TITLE
https connection seem broken with apl

### ISSUE THREAD

**Issue by Clueless76** [devopshq/artifactory#38]
Hi,

this morning I'm used the API by work and here what I can remember.

Following code was executed:

    from artifactory import ArtifactoryPath
    aql = ArtifactoryPath( "https://my-artifactory/artifactory", verify=False)
    artifacts = aql.aql("items.find", {"repo": "myrepo"})

When the line apl.apl was executed the connection could not verify SSL connection, even if the verification was set to false. 

Could somebody take an look?

Thanks,
Markus

**Comment by allburov** [comment]
Give us traceback and out 'pip freeze' command, please

**Comment by xyzmurali** [comment]
The issue is in the session.post call of function aql in class ArtifactoryPath. 
"verify=self.verify, cert=self.cert" has to be passed as part of this this call.

Replace
     r = self.session.post(aql_query_url, data=aql_query_text)
with
      r = self.session.post(aql_query_url, data=aql_query_text, verify=self.verify, cert=self.cert)

I do not have access to push this change, can someone with access push this change please.

**Comment by allburov** [comment]
@xyzmurali @Clueless76 We pass `cert` and `verify` to session https://github.com/devopshq/artifactory/commit/d1d6814ebd604cbf9fd11c4284b15c8c87e35bec 

Can you try install `develop` branch and check? 
```bash
python -m pip install git+https://github.com/devopshq/artifactory.git
```

**Comment by xyzmurali** [comment]
It worked. Thanks

**Comment by allburov** [comment]
Fix also available in master and pypi package. Thanks!
