### ISSUE TITLE
Feature request: Expose `lastUpdated` in `.stat()`

### ISSUE THREAD

**Issue by OddBloke** [devopshq/artifactory#380]
Artifactory does not perform deb metadata update synchronously: we've run into errors in automation due to this, and so we now have some logic which waits for the metadata we expect to be present. Having the `lastUpdated` timestamp available to us in `.stat()`s return would make this logic easier to implement: currently we directly call `artifact._accessor.get_stat_json(artifact)` to get access to it.

(Thanks again for this library: it continues to work really well for us!)

**Comment by OddBloke** [comment]
One potential solution to this, and a whole class of related requests, would be to store the JSON returned by Artifactory on the `ArtifactoryFileStat` object returned: then our code could do (e.g.) `artifact.stat().json['lastUpdated']`. (I could contribute this change if you'd like!)

**Comment by allburov** [comment]
Hi! 

It'd be better if `stat` function accepts the new `raw` parameter (`False` by default) and if it's set - save json response to `_json` field in `ArtifactoryFileStat` (None by default) and we can get access to original json by calling `json()` function.

So to access `lastUpdated` you'll need to run:
```
stat: ArtifactoryFileStat = artifact.stat(raw=True) 
raw_data: Dict = stat.json()
print(raw_data['lastUpdated']) 
```

>I could contribute this change if you'd like
It would be great!

**Comment by beliaev-maksim** [comment]
currently stats has `lastModified`, do you mean artifactory API provides additional output?
https://github.com/devopshq/artifactory/blob/5f8cb2e85e02da4bdd07ed913aaa19e39881f9c1/artifactory.py#L889


if yes, then why just not to include it the same way, what will be the purpose of getting raw data here?

**Comment by OddBloke** [comment]
Good point! I had thought that `ArtifactoryFileStat` was mimicking the return type of a stdlib stat interface (and so I didn't want to add another similar field to it), but looking again that isn't true.

`utime` doesn't feel quite right as a field name, I think the name collision with https://docs.python.org/3/library/os.html#os.utime would cause some confusion. How would we feel about following the Artifactory API and using `last_updated` (so my code would do `artifact.stat().last_updated`)?

**Comment by beliaev-maksim** [comment]
@OddBloke 
it is not `utime`, it is `mtime` -> `m` stands for modified

**Comment by beliaev-maksim** [comment]
what is the difference between last updated and last modified?

**Comment by OddBloke** [comment]
> @OddBloke it is not `utime`, it is `mtime` -> `m` stands for modified

Right, `mtime` already exists: I was talking about the potential _new_ name.

> what is the difference between last updated and last modified?

https://stackoverflow.com/a/69496989 is the best explanation I've found.

**Comment by beliaev-maksim** [comment]
@OddBloke
Got it, please submit a PR with an explicit name. I don't like current naming as well, but we should keep it for compatibility

**Comment by OddBloke** [comment]
I've submitted https://github.com/devopshq/artifactory/pull/382: I could also submit a follow-up which deprecates `mtime` and `ctime`, if you would like?
