### ISSUE TITLE
Lack of proxy connectivity support to remote jfrog repositories

### ISSUE THREAD

**Issue by miltlino** [devopshq/artifactory#389]
Hello, 
Do you plan to add any module to enable login and working with jfrog artifactory behind a proxy ?

**Comment by allburov** [comment]
Hi! 
You can control all `requests` options by passing `session` object to a new instance  https://github.com/devopshq/artifactory#session + https://requests.readthedocs.io/en/latest/user/advanced/#proxies

**Comment by miltlino** [comment]
Hello again,

Thank you for your response. 
One last question please. How is set the username and password there ?

**Comment by allburov** [comment]
The question is more about `requests` library, I think something like https://stackoverflow.com/questions/13506455/how-to-pass-proxy-authentication-requires-digest-auth-by-using-python-requests will help you
If not - please consult in `requests`s documentation about that case

**Comment by miltlino** [comment]
ok thank you :)
