### ISSUE TITLE
Property values are not URL quoted for matrix parameters

### ISSUE THREAD

**Issue by briantist** [devopshq/artifactory#408]
This only affects matrix parameters as far as I can tell; we should not quote parameters that are set after the fact because those go through a POST.

Because property values aren't encoded/quoted, it can cause undesirable characters to make it into properties, or cause the properties to be truncated. For example if your value contains a question mark `?`, it seems to get stripped somewhere; this character plus any characters after it do not end up in the property value.

If your value contains `%` followed by any hex value, the resulting character with that code will be inserted into the property value instead of the literal, for example if your value contains `%0` you'll end up with a null character in the value.

Example repros (can be done with the stock Artifactory OSS container):

```python
from artifactory import ArtifactoryPath

with open('/tmp/delme', 'w'):
    pass

a = Artifactorypath('http://localhost:8082/artifactory/example-repo-local', auth=('admin', 'password))

props = {
    'test1': 'a?b',
    'test2': 'a%3Fb',
    'test3': 'a%0b',
}

a.deploy_file('/tmp/delme', parameters=props)
```

---

I believe this should be fixable with [`urllib3.quote`](https://docs.python.org/3/library/urllib.parse.html#urllib.parse.quote) being applied to each version.

If this is an acceptable fix, I might be able to put up a PR for it.

If the position of the library is that callers are responsible for encoding their property values, then we must also make that explicit (because if callers quote their values now, and later the library adds quoting, it will double encode and ruin the values).

For the same reason, if we do opt to do quoting in the library, we should call it out as a breaking change.

**Comment by allburov** [comment]
>If this is an acceptable fix, I might be able to put up a PR for it.

It'd be great!

>it will double encode and ruin the values

I'm not sure how to detect this state... If we quote properties - it may broke the current usage. Is there a way to detect that properties have been quoted already?

What do you think about adding a parameter `quote_parameters` with the value `False` by default - and show all examples with `quote_parameters=True` in the documentation and later we can make it True by default in few releases?

**Comment by allburov** [comment]
It sounds amazing! :rocket:
