### ISSUE TITLE
Getting Repository parameters such as HandleReleases, HandleSnapshots

### ISSUE THREAD

**Issue by snssays** [devopshq/artifactory#410]
When making a get call  using find_repository_local, how do we access values such as handleReleases and handleSnapshots?

**Comment by snssays** [comment]
While sending, we were able to send it via repo.additional_params. But we are not able to access it once the repository is created and we get back the RepositoryLocal instance.

**Comment by donhui** [comment]
You can obtain the data you want through the following methods: 
```
repo = artifactory_.find_repository_local("maven-local")
print(repo.raw['handleReleases'])
 print(repo.raw['handleSnapshots'])
```

**Comment by snssays** [comment]
We were able to find it. Thanks for letting us know. That worked!
