### ISSUE TITLE
Unit tests failing with `IncompleteRead`

### ISSUE THREAD

**Issue by briantist** [devopshq/artifactory#419]
See the latest CI runs: https://github.com/devopshq/artifactory/actions

Errors include:
```
requests.exceptions.ChunkedEncodingError: ('Connection broken: IncompleteRead(236 bytes read, -236 more expected)', IncompleteRead(236 bytes read, -236 more expected))
urllib3.exceptions.IncompleteRead: IncompleteRead(236 bytes read, -236 more expected)
```

Should be fixed by https://github.com/getsentry/responses/pull/643 (thanks @beliaev-maksim!) but I wanted to open an issue to track that because:
- I spent a bit of time today trying to track it down and possibly fix it
- Assuming the above is the fix, we're waiting on a release on `responses`, and then we should update the dev requirements to set that version minimum probably: https://github.com/devopshq/artifactory/blob/master/requirements-dev.txt#L9

**Comment by beliaev-maksim** [comment]
no, we actually need to update tests on artifactory

we need to enable autocalculation of content length or provide header with the right content length
