### ISSUE TITLE
'children' does not give list of filenames, only sub-directory names

### ISSUE THREAD

**Issue by viggyprabhu** [devopshq/artifactory#44]
I understand this seems to be something very basic but when I use this library to get list of files from a certain Artifactory path, I notice that in 'children', I get only subdirectory names and no names of the files which are also present in the directory. I am not sure if this is because I am using an incompatible version of JFrog Artifactory which is 4.4.3

**Comment by viggyprabhu** [comment]
So I found out that this is happening when the files in the directory are "not locally present" in the artifactory server. When I click on any of the file in the browser, that is when it gets downloaded/cached in the server and I see a current date on it and also the file stats shows me as the creator of it. At very vague level, my understanding is that initially artifactory is just showing list of files and directory names in UI and only when someone tries to access the file, artifactory downloads it and makes it available to the user. Now since I am using listdir, the files which are not cached, does not get listed. However, if I directly try to access the Path through the library and call .open on the ArtifactoryPath object, it successfully opens and gives me access to the files. 
So assuming the above explanation was clear, the bug here is that though in Browser when I open, it shows me the filenames, when I access through the library, it does list me filenames as children of the directory. This mismatch is what needs to be fixed.

**Comment by beliaev-maksim** [comment]
@viggyprabhu 
are you sure it is not a limitation of JFrog API?
I have seen some issues that cached repos are represented as local repos in REST API

**Comment by beliaev-maksim** [comment]
need a reproducible case that is done in recent version of Artifactory. We use Artifactory Version 6.10.2 and all cached files available in the list of files

files should be listed via JFrog CLI, otherwise it is a limitation of Artifactory
