### ISSUE TITLE
No support for Python3.12

### ISSUE THREAD

**Issue by orim-orca** [devopshq/artifactory#449]
A lot of environments are already moving to Python3.12 and dohq artifactory does not support Python3.12

Main issue is the usage of pathlib._Flavour which is deprecated in Python3.12, which I'm not sure the usage of it here and how to rewrite

**Comment by ni-balexand** [comment]
Looks like a duplicate of #430

**Comment by allburov** [comment]
@ni-balexand yes, it's!
