### ISSUE TITLE
FEATURE REQUEST: adding `st_size` attribute to `ArtifactoryFileStat`

### ISSUE THREAD

**Issue by doronz88** [devopshq/artifactory#453]
Hi,

In many parts of my code I use `ArtifactoryPath` the same as `Path`. However, the `Path('').stat()` has a `st_size` attribute, while `ArtifactoryPath('').stat()` has only a `size` attribute. What do you think of adding a `st_size` attribute to `ArtifactoryFileStat` aswell, so code using both paths can access them both seamlessly? 

If you agree, I can create a PR for it.

Also, thanks for taking the gloves off and cotinuing this project! ❤️

**Comment by allburov** [comment]
> If you agree, I can create a PR for it.

Good idea, it'd be great!

**Comment by allburov** [comment]
Thank you for your contribution! :heart_hands: 

https://github.com/devopshq/artifactory/releases/tag/0.10.1
We're fixing the action issue, hopefully soon will be in pypi :crossed_fingers: https://github.com/devopshq/artifactory/actions/runs/10990572076/job/30511061714

**Comment by allburov** [comment]
done! https://pypi.org/project/dohq-artifactory/
