### ISSUE TITLE
User.update() fails with Bad request when updating the user

### ISSUE THREAD

**Issue by rafamunozg** [devopshq/artifactory#50]
What I'm trying to do is to update a user by adding groups to it. So, the user and groups exist beforehand, but when trying to update I get:

requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: https://_servername_/artifactory/api/security/users/_sampleuser_

Trying to replicate the operation using Postman, I think the problem because when you are updating the user you need to use the method Post, but the library is using Put to create (this is OK), but also to update, hence the bad request.

**Comment by cuichenli** [comment]
Hi there, looks like this issue has not been addressed yet. Can I just jump in and work on it? Roughly had a look and think it should be simple. 
I would basically create one extra parameter for `_create_and_update` to indicate it is going to use `put` or `post`, and the default value of it would be `post`. Or I can just separate the method into two different ones.
