### ISSUE TITLE
Using library to start artifact scan

### ISSUE THREAD

**Issue by hujarl** [devopshq/artifactory#51]
Looking for info on having this library kick off the artifact scan after upload.  Is that already built into the library?

**Comment by allburov** [comment]
@hujarl what do you mean by scanning?

**Comment by hujarl** [comment]
Apologies for the lack of clarity.

With Artifactory, assuming you also have the Xray tools, there are REST API calls to start a scan of the artifacts for known vulnerabilities  - 

https://www.jfrog.com/confluence/display/XRAY/Xray+REST+API#XrayRESTAPI-ScanArtifact

**Comment by allburov** [comment]
@hujarl Unfortunately, xray is another product and have its own API. For now there is no way to run a scan in this library.
But it's will be really useful do it with one python-library.
We would be grateful for the contribution to the community :)

**Comment by hujarl** [comment]
If I get it solved I will definitely share!

**Comment by beliaev-maksim** [comment]
XRay is a different tool and potentially should be handled in separate library, but with available use of artifactory objects
