### ISSUE TITLE
client is broken at a basic level

### ISSUE THREAD

**Issue by tsal** [devopshq/artifactory#52]
I can't even open a connection because the code is mangling the url scheme when it tries to join the API path to the provided URL. 

```
requests.exceptions.InvalidSchema: No connection adapters were found for '/api/storage/https:/hostname.jfrog.io/hostname/repo-folder'

```

**Comment by vicyap** [comment]
Do you know what version or commit you repro'd this at?

**Comment by norpol** [comment]
Might be related to #31.

**Comment by tsal** [comment]
at the time, it was from `pip3 install` but I don't remember the version that pulled; I'd tried the master branch as well. I abandoned python and went with Go for the solution so I don't even have that code anymore.
