### ISSUE TITLE
No support python 3.7

### ISSUE THREAD

**Issue by rafilkmp3** [devopshq/artifactory#54]
If i try use this with python 3.7.3 i get this error, i think this could be a issue from main artifatory package 

```
pip install dohq-artifactory
Python 3.7.3 (default, Mar 27 2019, 16:54:48)
[Clang 4.0.1 (tags/RELEASE_401/final)] :: Anaconda, Inc. on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import artifactory
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/rafael.sathler/projetos/hadoop-deploy/artifactory.py", line 1, in <module>
    from artifactory import ArtifactoryPath
ImportError: cannot import name 'ArtifactoryPath' from 'artifactory' (/Users/rafael.sathler/projetos/hadoop-deploy/artifactory.py)
```

but with python 2.7 i can import the module without problems
```

root@bf72a057cec9:/# python
Python 2.7.16 (default, Mar 27 2019, 09:43:28)
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from artifactory import ArtifactoryPath
>>> 
```

**Comment by allburov** [comment]
@rafilkmp3 
It looks like a local issue - you have a file with same name `artifactory`: `/Users/rafael.sathler/projetos/hadoop-deploy/artifactory.py` and you current workdir is `Users/rafael.sathler/projetos/hadoop-deploy/` or it path in the variable  `PYTHONPATH`

Could you repeat this in you environment and give me feedback. 
```
python --version
cd /
python -c 'import artifactory; print("ok")'
echo $PATHONPATH
```

If it will work - you need rename the file `hadoop-deploy/artifactory.py`.

**Comment by rafilkmp3** [comment]
thanks @allburov to help me  figure out, I renamed the file and now I can use the module
