### ISSUE TITLE
ask for new fields in ArtifactoryFileStat

### ISSUE THREAD

**Issue by qinrongx** [devopshq/artifactory#63]
Hi there,
  For prune purpose,  it seems the "Last Downloaded" timestamp is more valuable.
  If the artifact has been frequently downloaded and this timestamp got refreshed continuously, we will keep it in spite of its old "ctime" value.
  Please help check this.
  Thanks.

**Comment by allburov** [comment]
@qinrongx Where you want to use "Last Downloaded" properties? Could you give us example of code? 
It may not work for current library version, just show how you would like

**Comment by qinrongx** [comment]
Hi there,
Later on I found this property in https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API. :)
We tried to use this property to sort and then prune artifacts before.
