### ISSUE TITLE
build promotion

### ISSUE THREAD

**Issue by mentaal** [devopshq/artifactory#67]
Does this library support build promotion? I know that copying is metioned in the Readme but I'm looking to replace the otherwise flakey jenkins build promotion with a manual script. Just copying isn't enough because I want the artifacts within the build that I'm promoting to be updated to point to the new repository that I've promoted the build to. 

Thanks

**Comment by beliaev-maksim** [comment]
please check if #248 fixes it for you

**Comment by mentaal** [comment]
Thanks! Will do but it may be a while, I'm on a new project and will no doubt need this feature with it. 
For my last one I just rolled my own REST script to achieve this.

**Comment by beliaev-maksim** [comment]
@allburov please close as addressed by #248

**Comment by beliaev-maksim** [comment]
addressed by #248
