### ISSUE TITLE
[develop] Glob fails when urllib3 > 1.25

### ISSUE THREAD

**Issue by stac47** [devopshq/artifactory#68]
__This issue is linked to the develop branch__
With urllib3 > 1.25, the URL parsing is more constrained.

For instance, with urllib3==1.24.3:
```
> urllib3.util.parse_url('15.0.0.300')
Url(scheme=None, auth=None, host='15.0.0.300', port=None, path=None, query=None, fragment=None)
```
With urllib3==1.25, the same call leads to the following exception: `urllib3.exceptions.LocationParseError: Failed to parse: //15.0.0.300`

This introduction was to explain why when you are walking folder tree, it can occur that a folder is named '15.0.0.300'. In this case, the _ArtifactoryFlavour.splitroot method raise this exception since the function usrllib3.url.parse_url is called on every subfolder name.

```
File "/home/ubuntu/python_venv/artifactory-cleaner/lib/python3.6/site-packages/artifactory.py", line 360, in splitroot
    url = urllib3.util.parse_url(part)
  File "/home/ubuntu/python_venv/artifactory-cleaner/lib/python3.6/site-packages/urllib3/util/url.py", line 234, in parse_url
    raise LocationParseError(url)
urllib3.exceptions.LocationParseError: Failed to parse: //15.0.0.308
```

**Comment by allburov** [comment]
@stac47 thanks! This bug affected to our CI process too
