### ISSUE TITLE
is_file() raises when the artifacts' name contains square brackets

### ISSUE THREAD

**Issue by souris4science** [devopshq/artifactory#72]
The following exception is raised when is_file() method is called for an artifact where its name contains square branckets ('[' or ']'):

    if artifact.is_file():
  File "C:\Python37-32\lib\site-packages\artifactory.py", line 1035, in is_file
    return self._accessor.is_file(self)
  File "C:\Python37-32\lib\site-packages\artifactory.py", line 534, in is_file
    stat = self.stat(pathobj)
  File "C:\Python37-32\lib\site-packages\artifactory.py", line 492, in stat
    jsn = self.get_stat_json(pathobj)
  File "C:\Python37-32\lib\site-packages\artifactory.py", line 471, in get_stat_json
    raise RuntimeError(text)
RuntimeError: {
  "errors" : [ {
    "status" : 400,
    "message" : "Bad Request"
  } ]
}

**Comment by allburov** [comment]
@nikolasj could you help?

**Comment by nikolasj** [comment]
@souris4science, sorry for waiting.
It looks like a problem on API artifactory on older versions.
For example. I tried to make a request through the browser https://repo.jfrog.org/artifactory/api/storage/reponame/asdf[asdf.docx and received 400. Checked on the version of the artifactory 6.5.

But on version 6.11.1 everything works. I got 200.
What version of artifactory do you have?

**Comment by souris4science** [comment]
@nikolasj Artifactory version on our production deployment - in which I discovered the problem - is 5.11.0, but I can also try it out in a test deployment of artifactory with version 6.11.1.
Indeed, this seems to be an issue on artifactory side, but I thought that you could apply a workaround by escaping the special URL characters in the request and actually the square brackets.

**Comment by nikolasj** [comment]
@souris4science I'm afraid to get around the problem will not work.
I see the following solutions:
1. Do not use '[' if possible
2. Upgrade artifatory to the latest version.
3. Try to write about the problem in Jfrog. But they will say to update the artifactory))

**Comment by souris4science** [comment]
@nikolasj For the moment we avoid using such characters in the artifact paths. However my concern was whether such problems will pop up with other special characters as well. Anyway, let me check whether the problem is solved with artifactory 6.11.0, since we plan to upgrade to this version soon.

**Comment by nikolasj** [comment]
@souris4science Ok.
We will wait for your check on the artifactory version 6.11.0 to close the issue

**Comment by souris4science** [comment]
@nikolasj just checked the issue: in 6.11.1 it works just fine. 
Closing the issue.

**Comment by nabice** [comment]
is_file return False when filename contans "#"
@nikolasj
