### ISSUE TITLE
AttributeError: 'ArtifactoryPath' object has no attribute 'aql'

### ISSUE THREAD

**Issue by beyondan** [devopshq/artifactory#76]
Steps to reproduce:

1. Install `dohq-artifactory`, and then install `artifactory`
```
pip3 install dohq-artifactory
pip3 install artifactory
```

2. 
```
from artifactory import ArtifactoryPath
ArtifactoryPath('https://MY_URL', apikey='MY_API_KEY').aql
```

This happens because installing `artifactory` overwrites `SITE_PACKAGES/artifactory.py` that was also used by `dohq-artifactory`. Now I NEED to have both packages installed, and `dohq-artifactory` will always be installed before `artifactory`. 

I'm working on a pipeline that uses framework-plugin architecture.
The "framework" is some python script in a docker image, and `dohq-artifactory` is already installed in the image.

And the pipeline runs every night, and it goes like this...
Day 1:
1. Get a list of available plugins (uses AQL)
2. Install available "plugins" and their requirements (including `artifactory`)

Day 2:
1. Get a list of available plugins (uses AQL, but it fails because `artifactory` got installed yesterday)

I guess the questions are:

Why are there two separate packages in the first place? I'm using `dohq-artifactory` because it supports AQL (and some other neat enhancements I think). But couldn't these enhancements have happened in the original `artifactory` repo? And if you wanted to develop an entirely separate package, why keep the same file name? Why not just let users do `from dohq_artifactory import ArtifactoryPath`? I mean it's not as pretty as `from artifactory` but I feel like it's even worse to introduce conflicts with other PyPI packages. So basically you're forcing users to use one or the other. And even if you actually want to force users to use only one of these packages, this should be at least documented somewhere, or there should be a warning message during installation. 

What do you suggest I do in this situation? I don't want to have to go to every team manager and tell them to start using dohq-artifactory instead. You probably don't want to change the file name because that means all of your users will have to start using the new name.

**Comment by allburov** [comment]
@beyondan devopshq/artifactory is supported version for the original library parallels/artifactory. 
[parallels/artifactory/README.md](https://github.com/parallels/artifactory#this-repo-is-currently-outdated) tells us about it.
![image](https://user-images.githubusercontent.com/4376814/59898541-7afdec00-941b-11e9-84d9-fedecc55da19.png)

But if you was confused someone may be have the same question.
I will add information about it to README.md and pypi-package, thanks!

**Comment by allburov** [comment]
@beyondan I mean you don't needed anymore use `artifactory`-pypi package, use `dohq-artifactory`. We support all functional from original library

**Comment by allburov** [comment]
@beyondan It seems we can replace original `artifactory` - teams will continiue use `artifactory` but it will be support aql and other features.
Will be done in #77
