### ISSUE TITLE
Upload artifactory and dohq-artifactory to pypi

### ISSUE THREAD

**Issue by allburov** [devopshq/artifactory#77]
We have API KEY or we can contact with parallels, get permission to pypi and upload `dohq-artifactory` to pypi with two names:
1.  `artifactory` - we can replace it because we didn't do breaking changes
2. `dohq-artifactory` for backward compatibility in `requirements.in|txt`

It will close question like this #76

**Comment by allburov** [comment]
@Tim55667757 internall track id: CM-32482

**Comment by Tim55667757** [comment]
There is no easy way to make two deployments on Travis CI  to different repositories in PyPi. You can’t just take and renamed build and then push into another repository - PyPI does not allow this. The correct way is if the developers from Parallels pull our changes into their project and re-build it with their build-script, but they have not supported the project for a long time, as they wrote: https://github.com/Parallels/artifactory/blob/master/README .md#this-repo-is-currently-outdated

In your projects, you need to break the use of the old library  https://pypi.org/project/artifactory/ in advantage of the new library  https://pypi.org/project/dohq-artifactory/

Instructions for using the dohq-artifactory library you can be found here: https://devopshq.github.io/artifactory/
