### ISSUE TITLE
Drop support python <=3.4

### ISSUE THREAD

**Issue by allburov** [devopshq/artifactory#85]
@georgek has suggest dropping support python < 3.4 in #84
We can drop support 3.4 also, because this release has reached end-of-life.

What is a better python-way to do this? 

It will be cool if old versions of library will be available for python <=3.4 and new only for python > 3.4, how we do reach this?

```
pip3.4 install dohq-artifactory # find 0.4.112

pip3.7 install dohq-artifactory # will find 1.0.1, e.g
```

Classifier like `Programming Language :: Python :: 3.2` it's helpful metadata, but `pip` don't use it for search.

**Comment by allburov** [comment]
Easy way is require `dohq-artifactory<1` for python < 3.4, of course.

**Comment by allburov** [comment]
[PEP 427 The Wheel Binary Package Format 1.0](https://www.python.org/dev/peps/pep-0427/#file-name-convention) says that filename use `{python tag}` - **language implementation and version tag**, E.g. 'py27', 'py2', 'py3'.

We could upload `py35,py36,py37` wheels to pypi, but this way is too hard for supporting, imho. For a new python version we need to do some work.

So, I suggest support `python>3.4` for version `1.0.0` and add [python_requires](https://packaging.python.org/guides/distributing-packages-using-setuptools/#python-requires) to `setup.py`

**Comment by georgek** [comment]
I say just drop support. It relies on a backport of pathlib that is unmaintained. Are you going to backport fixes to the last version of this library for 3.4? Probably not.

If anyone really wants to install the old versions for Python<=3.4 then they can pin their dependency to the last one that works.

If support is to be dropped after 1.0.0 then a deprecation warning could be added to 1.0.0 when imported with Python<=3.4.

**Comment by cowlinator** [comment]
`It will be cool if old versions of library will be available for python <=3.4`
The way I interpret this is that `old version` implies zero backporting, zero maintenance, forever.

I support this idea.  We don't want to force every single developer to have to individually re-discover which logacy version of `dohq-artifactory` works with their legacy version of python. Instead of each and every one of them pinning their dependency, how about we do it for them, one time, forever?

**Comment by georgek** [comment]
Sure, if you can figure out a way to do that. But I don't think there is a way without having them pin their dependencies. You could generate the `py35,py36,py37` wheels but then you'll have to keep making new ones for `py38` etc. Is it really worth it to help people who should be upgrading their old version of Python anyway?

**Comment by cowlinator** [comment]
Yes.
