### ISSUE TITLE
Add complex AQL example to README.md

### ISSUE THREAD

**Issue by sushant-pradhan** [devopshq/artifactory#86]
Hello, I intend to use the following aql. Can you please suggest how can it be formed using the python object?
items.find({"$or":[{"repo": "docker-prod"}], "type":"file","created" : {"$gt" : "2019-07-10T19:20:30.45+01:00"}}).include("repo","path","name",).sort({"$asc" : ["repo", "path", "name"]})

I can get the json created till fin but I am unable to append .include() and .sort()

**Comment by Kirlocca** [comment]
You might have some more parenthesis issues in your query. I have tried to interpred your query: 

> The query will find all items in repo _docker-prod_ that are of type _file_ and were created after _timecode_. The query will only display the fields "repo", "path" and "name" and will sort the result ascendingly by those fields. 

 You might want to put this query in a python object like that: 
```
aqlargs = ["items.find", {"$and": [
  {
    "repo": "docker-prod"
  }, 
  {
    "type": "file"
  },
  {
    "created" : {"$gt" : "2019-07-10T19:20:30.45+01:00"}
  }
]},
".include", ["repo","path","name"], 
".sort", {"$asc" : ["repo", "path", "name"]}
]
```
and send the query via 
`
list_of_artifact_objects = artifactory.aql(*aqlargs)
`

Does this answer your question?

**Comment by nikolasj** [comment]
Hi @an-sush! Did you manage to check the option suggested in [the comment](https://github.com/devopshq/artifactory/issues/86#issuecomment-534528242)?
Can I close the task?

**Comment by allburov** [comment]
Probably, we should add the above example to readme.md and close the issue. What do you think?
