### ISSUE TITLE
The function splitroot() does not work for Cloud Enterprise artifactory repos

### ISSUE THREAD

**Issue by ainskeep** [devopshq/artifactory#88]
Our Cloud Enterprise repo name path is organized like this:

https://<Company_name>.jfrog.io/<Company_name>/

the function splitroot() in _ArtifactoryFlavour assumes the format:

http://mysite/artifactory

and attempts to parse based on /artifactory/
It was incorrectly parsed in my use case and I needed to hardcode <Company_name> in place of /artifactory/ 
To support more use cases, an option to pass in the "Drive" and "path" separately into the ArtifactoryPath constructor to bypass the parsing would be very nice

**Comment by alanyee** [comment]
This issue was addressed in #108 and #109. @Tim55667757 can you please close this issue?

**Comment by alanyee** [comment]
nvm, given #115, the problem still lives on.

**Comment by alanyee** [comment]
```
from artifactory import global_config

global_config['https://<Company_name>.jfrog.io/<Company_name>'] = {'username': 'user', 'password': 'pwd', 'verify': True, 'cert': None}
```
is an interesting workaround

**Comment by allburov** [comment]
Could you test the develop branch of the library for Artifactory SaaS?

https://github.com/devopshq/artifactory#artifactory-saas
```python
# pip install git+https://github.com/devopshq/artifactory.git
from artifactory import ArtifactorySaaSPath

# API_KEY
path = ArtifactorySaaSPath(
    "https://myartifactorysaas.jfrog.io/myartifactorysaas/folder/path.xml",
    apikey="MY_API_KEY",
)
```

**Comment by ainskeep** [comment]
I can confirm that the new ArtifactorySaaSPath works for our SaaS installation. Thank you for fixing this!
