### ISSUE TITLE
Support for implementing Property Sets

### ISSUE THREAD

**Issue by cmccluskey** [devopshq/artifactory#91]
Per https://www.jfrog.com/confluence/display/RTF/Properties#Properties-PropertySets --

Are there any plans to be able to create/modify a property set, and have the ability to apply that Property Set to a Repo?

**Comment by beliaev-maksim** [comment]
Hi @cmccluskey,
how does that different from https://www.jfrog.com/confluence/display/JFROG/Artifactory+REST+API#ArtifactoryRESTAPI-SetItemProperties ?
this is implemented here: https://github.com/devopshq/artifactory#artifact-properties

for more details you can see function `set_properties`


if it is not what you are looking for, can you give more info?
