### ISSUE TITLE
Fetch all users, groups, permission targets

### ISSUE THREAD

**Issue by Arlington1985** [devopshq/artifactory#98]
Is there any way to get all the users, groups, permission targets, tokens without specifying any name?

**Comment by nikolasj** [comment]
Hi @Arlington1985! 
I do not quite understand what you need. Can you give examples?

**Comment by Arlington1985** [comment]
I mean is there any function like `users = artifactory_.get_all_users("*")` ? Same with applying for _group_ and _permission targets_.

**Comment by allburov** [comment]
Artifactory supports [this](https://www.jfrog.com/confluence/display/RTF/Artifactory+REST+API#ArtifactoryRESTAPI-GetUsers), but we didn't implement method .

`get_users|groups,permissions` would be perfect method!

**Comment by beliaev-maksim** [comment]
@allburov 
can you close this PR?

**Comment by beliaev-maksim** [comment]
addressed by #141
